(function(root){
'use strict';
const labels={pending:'待审核',approved:'已通过 · 月份已定稿',rejected:'已退回',withdrawn:'已撤回'};
const money=n=>Number(n??0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const eligible=c=>c.eligible===true && !c.batch_id;
const errors={sales_forbidden:'没有这项操作权限',sales_locked:'订单已被提交或不属于本人，请刷新',sales_version:'记录已更新，请刷新后重试',sales_month_closed:'该月份已经提交或定稿，不能再次申报',sales_not_received:'选中的订单尚未确认收货，或采集暂时没有这笔订单',sales_received_required:'手动订单标为已收货时必须填写收货日期',sales_received_future:'收货日期不能晚于今天',sales_select_orders:'请先选择要申报的订单',sales_images_required:'请提供 1–12 张聊天截图',sales_image_invalid:'图片尚未上传成功或格式、大小不符合要求',sales_order_required:'请关联至少一笔订单',sales_order_missing:'当前采集未找到该订单，请重新搜索',sales_order_claimed:'这笔订单已被认领，不能重复登记',sales_adjustment_reason:'调整金额时请填写退款、差价或补款原因',sales_source_changed:'订单或金额已更新，请刷新核对后重新提交',sales_self_review:'不能审核本人的提成单，请由另一位审核人处理',sales_reject_reason:'请填写退回原因',sales_search_minimum:'请输入至少 4 位订单号后点击搜索',sales_reference_duplicate:'这笔手动单号已经登记过',sales_amount:'计提金额不能为负数',sales_month_invalid:'请选择有效月份，不能申报未来月份',sales_buyer_required:'请填写微信号、旺旺号或微信昵称',sales_title:'请填写销售内容',sales_progress:'请选择订单进度'};
root.JUN_SALES={labels,eligible,money};if(typeof module!=='undefined')module.exports=root.JUN_SALES;if(typeof document==='undefined')return;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'});
let month=new URLSearchParams(location.search).get('month')||today().slice(0,7),data,tab='claims',busy=false,sequence=0,selected=new Set(),archive=null;
async function api(path='',values){const r=await fetch('/api/customer/sales'+path,values?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)}:undefined);const d=await r.json();if(!r.ok)throw new Error(errors[d.error]||d.detail||d.error||'请求失败');return d;}
function message(text){$('#sales-message')?.remove();const e=document.createElement('div');e.id='sales-message';e.className='alert alert-danger';e.textContent=text;$('#module-content').before(e);}
function modal(title,body){const d=document.createElement('dialog');d.className='sales-dialog';d.innerHTML=`<header><strong>${esc(title)}</strong><button class="btn btn-sm" type="button" data-close aria-label="关闭">×</button></header><div class="sales-body">${body}</div>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.showModal();return d;}
function orderText(o){return `${o.id} · ${o.trade_status||'状态未提供'} / ${o.process_status||''} · ¥${money(o.amount)}`;}
function orderPreview(o){return `<strong>订单 ${esc(o.id)}</strong><div class="sales-meta"><span>${esc(o.trade_status||'状态未提供')} / ${esc(o.process_status||'')}</span><strong>订单金额 ¥${money(o.amount)}</strong></div>${o.title?`<p>${esc(o.title)}</p>`:''}<div class="table-responsive"><table class="table table-sm"><thead><tr><th>款式／款号</th><th>规格</th><th>数量</th><th>单价</th><th>金额</th></tr></thead><tbody>${(o.items||[]).map(i=>`<tr><td>${esc(i.name||'')}<br><small>${esc(i.sku||'—')}</small></td><td>${esc([i.color,i.size].filter(Boolean).join(' / ')||'—')}</td><td>${esc(i.qty??'—')}</td><td>${i.unit_price==null?'—':'¥'+money(i.unit_price)}</td><td>${i.amount==null?'—':'¥'+money(i.amount)}</td></tr>`).join('')}</tbody></table></div>`;}
function claimCard(c,check=false){const dates=c.kind==='linked'?(c.orders||[]).map(o=>`收货：${o.received_date|| (o.received?'已确认，采集未提供日期':'未确认')}；采集：${o.captured_at||'—'}`).join('\n'):`收货日期：${c.received_date||'未填写'}`;return `<article class="sales-card"><header><h3>${check?`<input type="checkbox" aria-label="选择 ${esc(c.title)}" data-select="${c.id}" ${selected.has(c.id)?'checked':''} ${eligible(c)?'':'disabled'}> `:''}${esc(c.title)}</h3><span class="sales-chip">${c.kind==='linked'?'关联订单':'手动输入订单'} · ${c.eligible?'可申报':'待收货／待核对'}</span></header><div class="sales-meta"><span>${esc(c.buyer||'')}</span>${c.kind==='manual'?`<span>单号 ${esc(c.manual_order_no||c.reference||'—')}</span>`:''}<span>计提金额 ¥${money(c.claim_amount)}</span><strong>提成 ¥${money(c.commission)}</strong></div>${(c.orders||[]).map(o=>`<div class="sales-hint">${esc(orderText(o))}</div>`).join('')}<div class="sales-hint sales-note">${esc(dates)}</div>${Number(c.adjustment)?`<div class="sales-note">金额调整 ${money(c.adjustment)}：${esc(c.adjustment_reason)}</div>`:''}<div class="sales-actions mt-2"><button class="btn btn-sm" data-detail="${c.id}" data-kind="claim">截图与记录</button>${check&&data.can_submit?`<button class="btn btn-sm" data-edit="${c.id}">编辑</button>`:''}</div></article>`;}
function render(){
 const closed=data.closed_months.includes(month);const chosen=data.claims.filter(c=>selected.has(c.id)&&eligible(c));
 $('#module-toolbar').innerHTML=`<div class="sales-toolbar"><button class="btn ${tab==='claims'?'btn-primary':''}" data-tab="claims">销售登记</button><button class="btn ${tab==='months'?'btn-primary':''}" data-tab="months">月度提成与审核</button><button class="btn ${tab==='archive'?'btn-primary':''}" data-tab="archive">历史原表</button><label>申报／查看月份 <input id="sales-month" type="month" class="form-control" value="${esc(month)}" max="${today().slice(0,7)}"></label>${data.can_submit?'<button class="btn btn-primary" data-new>＋ 登记销售</button>':''}<button class="btn" data-refresh>刷新</button></div>`;
 if(tab==='claims')$('#module-content').innerHTML=`<p class="sales-hint">平时登记无需审批。已收货的订单可勾选申报；未选订单继续留在这里。关联订单以最新采集为准。</p>${data.can_submit?`<div class="sales-submission"><strong>${esc(month)} 月度提成</strong><div class="sales-meta">已选 ${chosen.length} 笔 · 计提金额 ¥${money(chosen.reduce((s,c)=>s+Number(c.claim_amount),0))} · 提成 ¥${money(chosen.reduce((s,c)=>s+Number(c.commission),0))}</div>${closed?'<p>本人该月份已提交或定稿，不能新增申报。请选择其他月份；查看原单请进入“月度提成与审核”。</p>':'<p class="sales-hint">确认收货即可申请。申报月份由本人核对；系统保留真实收货信息，跨月不会重复计提。</p>'}<button class="btn btn-primary" data-submit ${closed?'disabled':''}>确认并提交本月提成</button></div>`:''}${data.claims.map(c=>claimCard(c,true)).join('')||'<div class="sales-empty">还没有未申报的销售记录，点击“登记销售”开始。</div>'}`;
 else if(tab==='archive')$('#module-content').innerHTML=`<p class="sales-hint">原表只读档案，保留原值及图片，不代表已审核或已发放。合并单元格请点开查看对应位置，未自动重算历史提成。</p><div class="sales-toolbar"><label>原表结算月 <select id="archive-month" class="form-select">${!(archive?.months||[]).includes(month)?`<option value="${esc(month)}">${esc(month)}（无记录）</option>`:''}${(archive?.months||[]).map(m=>`<option value="${esc(m||'')}" ${m===month?'selected':''}>${esc(m||'未填写月份')}</option>`).join('')}</select></label></div>${(archive?.rows||[]).map(r=>`<article class="sales-card"><h3>原表第 ${r.source_row} 行 · ${esc(r.cells['B'+r.source_row]?.v||'合并／续行')}</h3><div class="sales-meta"><span>订单号 ${esc(r.cells['C'+r.source_row]?.v||'—')}</span><span>原金额 ${esc(r.cells['E'+r.source_row]?.v||'—')}</span><span>原提成 ${esc(r.cells['K'+r.source_row]?.v||'未填写')}</span></div><button class="btn btn-sm" data-detail="${r.id}" data-kind="archive">原值、备注与图片（${r.image_count}）</button></article>`).join('')||'<p>本月无原表记录。</p>'}`;
 else $('#module-content').innerHTML=`<p class="sales-hint">每人每月一份提成单。提交后可修改订单，所有修改留痕；审核通过后该月份关闭申报；后续收货订单留待其他月份申请。</p>${data.batches.map(b=>`<article class="sales-card"><header><h3>${esc(b.month)} · ${esc(b.owner_name)}</h3><span class="sales-chip ${b.status}">${labels[b.status]}</span></header><div class="sales-meta"><span>${b.items.length} 笔</span><span>计提金额 ¥${money(b.amount)}</span><strong>提成 ¥${money(b.commission)}</strong></div>${b.reason?`<p class="sales-note">处理意见：${esc(b.reason)}</p>`:''}<div class="sales-actions"><button class="btn" data-detail="${b.id}" data-kind="batch">明细、截图与审批记录</button>${b.status==='pending'&&b.owner_id===data.user_id&&data.can_submit?`<button class="btn" data-action="withdraw" data-id="${b.id}">撤回修改</button>`:''}${b.status==='pending'&&b.owner_id!==data.user_id&&data.can_approve?`<button class="btn btn-success" data-action="approve" data-id="${b.id}">批准并定稿</button><button class="btn btn-outline-danger" data-action="reject" data-id="${b.id}">退回修改</button>`:''}</div></article>`).join('')||'<div class="sales-empty">该月份暂无提成单。</div>'}`;
}
async function load(){const seq=++sequence;const result=await api('?month='+encodeURIComponent(month));if(seq!==sequence)return;data=result;if(tab==='archive'){const a=await api('/archive?month='+encodeURIComponent(month));if(seq!==sequence)return;archive=a;}selected=new Set([...selected].filter(id=>data.claims.some(c=>c.id===id&&eligible(c))));render();}
async function mutate(action,values){if(busy)return;busy=true;try{await api('',{action,values});await load();return true;}catch(e){message(e.message);return false;}finally{busy=false;}}
async function compress(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('请选择 JPG、PNG 或 WebP 图片');const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>40000000)throw new Error('图片像素过大，请拆成多张截图以保持文字清晰');const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);const blob=await new Promise(r=>canvas.toBlob(r,'image/webp',.85));const best=blob&&blob.size<file.size?blob:file;if(best.size>12582912)throw new Error('压缩后仍超过 12 MB，请拆分截图');return best;}finally{bitmap.close();}}
function editor(c){
 let orders=[...(c?.orders||[])],attachments=[...(c?.attachments||[])];
 const d=modal(c?'编辑销售':'登记企业微信销售',`<form id="sales-edit"><div class="sales-fields"><label class="wide">订单类型<select class="form-select" name="kind"><option value="linked">关联系统订单</option><option value="manual">手动输入订单</option></select></label><div class="wide" id="linked-area"><div class="sales-search"><input class="form-control" id="order-query" placeholder="输入订单号，点击搜索才会查询" minlength="4" maxlength="100"><button type="button" class="btn" id="order-search">搜索</button></div><div id="order-results"></div><div id="order-selected"></div></div><label class="wide"><span id="buyer-label">旺旺号（可补全）</span><input class="form-control" name="buyer" required maxlength="100" value="${esc(c?.buyer)}"></label><div id="manual-number" class="wide"><span>手动订单号</span><p class="sales-hint">${esc(c?.manual_order_no||'保存后自动生成，无需填写')}</p></div><label class="wide" id="manual-title">款式／款号／销售内容<input class="form-control" name="title" maxlength="300" value="${esc(c?.title)}"></label><label id="manual-amount">订单金额<input class="form-control" name="amount" type="number" min="0" step=".01" value="${esc(c?.amount??0)}"></label><label id="manual-progress">订单进度<select class="form-select" name="progress"><option>未发货</option><option>已发货</option><option>已收货</option></select></label><label id="manual-received">确认收货日期<input class="form-control" name="received_date" type="date" max="${today()}" value="${esc(c?.received_date||'')}"></label><label id="manual-adjustment">退款／补款调整（选填，减少填负数）<input class="form-control" name="adjustment" type="number" step=".01" value="${esc(c?.adjustment??0)}"></label><label id="manual-adjustment-reason">调整原因<input class="form-control" name="adjustment_reason" maxlength="1000" value="${esc(c?.adjustment_reason)}"></label><div class="wide"><label>聊天截图（必须提供，最多 12 张）<input class="form-control" name="images" type="file" accept="image/png,image/jpeg,image/webp" multiple></label><p class="sales-hint">自动压缩，保留文字清晰度。原有 ${attachments.length} 张；新增图片保存时上传。</p><div id="local-previews" class="sales-images"></div><div id="saved-images"></div></div><label class="wide">备注（选填）<textarea class="form-control" name="note" maxlength="2000">${esc(c?.note)}</textarea></label></div><div class="sales-error" id="edit-error" role="alert"></div><footer><button class="btn btn-primary" type="submit">保存登记</button></footer></form>`);
 const form=d.querySelector('form'),el=form.elements;el.kind.value=c?.kind||'linked';el.progress.value=c?.progress||'未发货';let uploads=[],localUrls=[];let buyerEdited=Boolean(c?.buyer&&c.buyer!==[...new Set(orders.map(o=>o.buyer||'').filter(Boolean))].join(' / '));el.buyer.oninput=()=>{buyerEdited=true;};
 const showOrders=()=>{d.querySelector('#order-selected').innerHTML=orders.map(o=>`<div class="sales-order">${orderPreview(o)}<button type="button" class="btn btn-sm" data-remove-order="${esc(o.id)}">移除关联</button></div>`).join('');if(el.kind.value==='linked'){if(!buyerEdited)el.buyer.value=[...new Set(orders.map(o=>o.buyer||'').filter(Boolean))].join(' / ');el.amount.value=orders.reduce((sum,o)=>sum+Number(o.amount||0),0).toFixed(2);el.title.value=orders.map(o=>o.title||(o.items||[]).map(i=>[i.sku,i.name].filter(Boolean).join(' ')).join('、')||o.id).join('；').slice(0,300);}};
 function sync(){const linked=el.kind.value==='linked';d.querySelector('#linked-area').hidden=!linked;for(const id of ['manual-number','manual-title','manual-amount','manual-progress','manual-received','manual-adjustment','manual-adjustment-reason'])d.querySelector('#'+id).hidden=linked;d.querySelector('#buyer-label').textContent=linked?'旺旺号（自动带入，可补全）':'微信号／旺旺号／微信昵称';el.amount.readOnly=linked;el.title.readOnly=linked;el.title.required=!linked;el.amount.required=!linked;el.received_date.required=!linked&&el.progress.value==='已收货';el.adjustment_reason.required=!linked&&Number(el.adjustment.value)!==0;showOrders();}
 el.kind.onchange=sync;el.progress.onchange=sync;el.adjustment.oninput=sync;sync();
 async function savedImages(){if(!c)return;try{const detail=await api('/detail?id='+c.id+'&kind=claim');d.querySelector('#saved-images').innerHTML=attachments.map(p=>`<div class="sales-images"><a href="${esc(imageUrl(detail.urls[p]))}" target="_blank" rel="noopener"><img src="${esc(imageUrl(detail.urls[p]))}" alt="原有聊天截图"></a><button class="btn btn-sm" type="button" data-remove-image="${esc(p)}">移除</button></div>`).join('');}catch(e){d.querySelector('#edit-error').textContent=e.message;}}
 savedImages();
 el.images.onchange=()=>{uploads=[];localUrls.forEach(URL.revokeObjectURL);localUrls=[...el.images.files].map(f=>URL.createObjectURL(f));d.querySelector('#local-previews').innerHTML=localUrls.map(u=>`<img src="${u}" alt="待上传聊天截图">`).join('');};d.addEventListener('close',()=>localUrls.forEach(URL.revokeObjectURL));
 let searching=false;async function search(){if(searching)return;const q=d.querySelector('#order-query').value.trim();if(q.length<4){d.querySelector('#edit-error').textContent=errors.sales_search_minimum;return;}searching=true;d.querySelector('#order-search').disabled=true;try{const result=await api('?q='+encodeURIComponent(q));d.querySelector('#order-results').innerHTML=result.orders.map((o,i)=>`<div class="sales-order"><div>客户 ${esc(o.buyer)}</div>${orderPreview(o)}<button type="button" class="btn btn-sm" data-pick="${i}" ${o.claimed&&!orders.some(x=>x.id===o.id)?'disabled':''}>${o.claimed&&!orders.some(x=>x.id===o.id)?'已被认领':'关联'}</button></div>`).join('')||'<p>当前采集未找到此订单。可核对单号，微信直接付款请选手动订单。</p>';d.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{const o=result.orders[Number(b.dataset.pick)];if(!orders.some(x=>x.id===o.id))orders.push(o);showOrders();d.querySelector('#order-results').innerHTML='';});}catch(e){d.querySelector('#edit-error').textContent=e.message;}finally{searching=false;d.querySelector('#order-search').disabled=false;}}
 d.querySelector('#order-search').onclick=search;d.querySelector('#order-query').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();search();}};
 d.addEventListener('click',e=>{const r=e.target.closest('[data-remove-order]');if(r){orders=orders.filter(o=>o.id!==r.dataset.removeOrder);showOrders();}const a=e.target.closest('[data-remove-image]');if(a){attachments=attachments.filter(p=>p!==a.dataset.removeImage);a.parentElement.remove();}});
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;try{const files=[...el.images.files];if(attachments.length+files.length<1||attachments.length+files.length>12)throw new Error(errors.sales_images_required);if(el.kind.value==='linked'&&!orders.length)throw new Error(errors.sales_order_required);
 for(let i=uploads.length;i<files.length;i++){button.textContent=`正在压缩上传 ${i+1}/${files.length}`;const blob=await compress(files[i]);const ticket=await api('/upload',{type:blob.type,size:blob.size});const {error}=await window.JUN_SUPABASE.storage.from(ticket.bucket).uploadToSignedUrl(ticket.path,ticket.token,blob,{contentType:blob.type});if(error)throw error;uploads.push(ticket.path);}
 const v=Object.fromEntries(new FormData(form));delete v.images;Object.assign(v,{id:c?.id,version:c?.version,order_ids:orders.map(o=>o.id),attachments:[...attachments,...uploads]});await api('',{action:'save',values:v});d.close();await load();}catch(e){d.querySelector('#edit-error').textContent=e.message;}finally{button.disabled=false;button.textContent='保存登记';}};
}
function imageUrl(url){if(!url)return '';const at=url.indexOf('/storage/v1/');if(at<0)return '';return window.JUN_CONFIG.supabaseUrl.replace(/\/$/,'')+url.slice(at);}
function evidence(c,urls){c={...c,claim_amount:c.claim_amount??(Number(c.amount||0)+Number(c.adjustment||0)),commission:c.commission??Math.round((Number(c.amount||0)+Number(c.adjustment||0))*5)/100};return `<h4>${esc(c.title)}</h4><p>${c.kind==='linked'?'关联订单':'手动输入订单'} · 计提金额 ¥${money(c.claim_amount)} · 提成 ¥${money(c.commission)}</p><p>${esc(c.buyer||'')}${c.kind==='manual'?' · 单号 '+esc(c.manual_order_no||c.reference||'—'):''}</p>${(c.orders||[]).map(orderPreview).join('')}<p class="sales-note">${esc(c.note)}${c.adjustment_reason?'\n调整 '+money(c.adjustment)+'：'+esc(c.adjustment_reason):''}</p><div class="sales-images">${(c.attachments||[]).map(p=>`<a href="${esc(imageUrl(urls[p]))}" target="_blank" rel="noopener"><img loading="lazy" src="${esc(imageUrl(urls[p]))}" alt="聊天截图，点击查看清晰图"></a>`).join('')}</div>`;}
function archiveEvidence(r,urls){const names={B:'旺旺号',C:'订单号',E:'金额',F:'确认收货',H:'付款方式／补充说明',I:'备注1',J:'备注2',K:'提成金额',L:'提成结算月'};return `<h3>原表第 ${r.source_row} 行 · ${esc(r.month||'结算月未填写')}</h3>${Object.entries(r.cells).filter(([a,c])=>c.v||c.f).map(([a,c])=>`<p class="sales-note"><strong>${esc(names[a.replace(/\d/g,'')]||a)}（${a}）</strong>：${esc(a.startsWith('L')&&r.month?r.month:c.v)}${c.f?`<small>　公式 ${esc(c.f)}</small>`:''}</p>`).join('')}<p class="sales-hint">相关合并单元格：${esc((r.merges||[]).join('、')||'无')}</p><div class="sales-images">${(r.attachments||[]).map(p=>`<a href="${esc(imageUrl(urls[p]))}" target="_blank" rel="noopener"><img loading="lazy" src="${esc(imageUrl(urls[p]))}" alt="原表截图"></a>`).join('')}</div>`;}
async function detail(id,kind){const d=modal('销售明细','正在读取…');try{const r=await api('/detail?id='+id+'&kind='+kind);const editable=kind==='batch'&&r.record.status==='pending'&&(data.can_approve||r.record.owner_id===data.user_id&&data.can_submit);d.querySelector('.sales-body').innerHTML=(kind==='archive'?archiveEvidence(r.record,r.urls):kind==='batch'?`<h3>${esc(r.record.month)} · ${labels[r.record.status]}</h3>${r.record.items.map(c=>evidence(c,r.urls)+(editable?`<button class="btn btn-sm" data-edit-pending="${c.id}">编辑订单</button>`:'')).join('<hr>')}`:evidence(r.record,r.urls)+(r.can_edit?`<button class="btn" data-edit-pending="${r.record.id}">编辑订单</button>`:''))+(data.can_approve?`<h3>修改与审批记录</h3>${r.history.map(h=>`<details class="sales-history"><summary>${esc(h.created_at)} · ${esc(h.actor_name)} · ${esc(({save:'保存登记',edit:'修改订单并更新月单',submit:'提交定稿',approve:'审核通过',reject:'退回修改',withdraw:'撤回'})[h.action]||h.action)}</summary>${h.payload.reason?`<p>${esc(h.payload.reason)}</p>`:''}${h.payload.before?'<h4>修改前</h4>'+evidence(h.payload.before,r.urls):''}${h.payload.after?'<h4>修改后</h4>'+evidence(h.payload.after,r.urls):''}${(h.payload.items||[]).map(c=>evidence(c,r.urls)).join('<hr>')}</details>`).join('')}`:'');}catch(e){d.querySelector('.sales-body').textContent=e.message;}}
async function editPending(id,dialog){try{const r=await api('/detail?id='+id+'&kind=claim');if(!r.can_edit)throw new Error('该订单已经定稿，不能修改');dialog?.close();editor(r.record);}catch(e){message(e.message);}}
function confirmAction(action,b){const d=modal(action==='submit'?'确认月度提成单':({approve:'批准并定稿',reject:'退回修改',withdraw:'撤回提成单'})[action],`<form><p>${action==='submit'?`${esc(month)}：确认本月订单已经选齐。提交后仍可编辑订单，修改自动留痕；批准后该月份不能再改动。`:action==='approve'?'批准后，这份月单及申报月份固定，后续新增订单需申报其他月份。':action==='withdraw'?'撤回后本月重新可编辑，原提交记录仍保留。':'填写需要修改的内容，申请人修改后重新提交。'}</p>${action==='reject'?'<textarea class="form-control" name="reason" required maxlength="1000" placeholder="退回原因"></textarea>':''}<footer><button class="btn btn-primary" type="submit">确认${action==='submit'?'提交':''}</button></footer></form>`);d.querySelector('form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('button');btn.disabled=true;const claims=data.claims.filter(c=>selected.has(c.id)&&eligible(c));const values=action==='submit'?{month,ids:claims.map(c=>c.id),expected:claims.map(c=>({id:c.id,version:c.version,amount:c.claim_amount,orders:c.orders}))}:{id:b.id,version:b.version,reason:new FormData(e.target).get('reason')||''};if(await mutate(action,values)){d.close();if(action==='submit'){selected.clear();tab='months';render();}}else {btn.disabled=false;let err=d.querySelector('.sales-error');if(!err){err=document.createElement('p');err.className='sales-error';d.querySelector('form').prepend(err);}err.textContent=$('#sales-message')?.textContent||'提交失败，请重试';}};}
document.addEventListener('change',e=>{if(e.target.id==='archive-month'){month=e.target.value;load().catch(e=>message(e.message));}if(e.target.id==='sales-month'){month=e.target.value;if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))return;selected.clear();const u=new URL(location);u.searchParams.set('month',month);history.replaceState(null,'',u);load().catch(e=>message(e.message));}if(e.target.matches('[data-select]')){e.target.checked?selected.add(e.target.dataset.select):selected.delete(e.target.dataset.select);render();}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){tab=b.dataset.tab;if(tab==='archive')load().catch(e=>message(e.message));else render();}if(b.hasAttribute('data-new'))editor();if(b.dataset.editPending)editPending(b.dataset.editPending,b.closest('dialog'));if(b.dataset.edit)editor(data.claims.find(c=>c.id===b.dataset.edit));if(b.dataset.detail)detail(b.dataset.detail,b.dataset.kind);if(b.hasAttribute('data-refresh'))load().catch(e=>message(e.message));if(b.hasAttribute('data-submit'))confirmAction('submit');if(b.dataset.action)confirmAction(b.dataset.action,data.batches.find(x=>x.id===b.dataset.id));});
Promise.resolve(window.JUN_AUTH_READY).then(load).catch(e=>message(e.message));
})(typeof window!=='undefined'?window:globalThis);
