(function(root){
'use strict';
const labels={pending:'待审核',approved:'已通过 · 月份已定稿',rejected:'已退回',withdrawn:'已撤回'};
const money=n=>Number(n??0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const eligible=c=>c.eligible===true && !c.batch_id;
const errors={sales_forbidden:'没有这项操作权限',sales_locked:'订单已被提交或不属于本人，请刷新',sales_version:'记录已更新，请刷新后重试',sales_month_closed:'该月份已经提交或定稿，不能再次申报',sales_not_received:'选中的订单尚未确认收货，或采集暂时没有这笔订单',sales_received_required:'手动订单标为已收货时必须填写收货日期',sales_received_future:'收货日期不能晚于今天',sales_select_orders:'请先选择要申报的订单',sales_images_required:'请提供 1–12 张聊天截图',sales_image_invalid:'图片尚未上传成功或格式、大小不符合要求',sales_order_required:'请关联至少一笔订单',sales_order_missing:'当前采集未找到该订单，请重新搜索',sales_order_claimed:'这笔订单已被认领，不能重复登记',sales_adjustment_reason:'调整金额时请填写退款、差价或补款原因',sales_source_changed:'订单或金额已更新，请刷新核对后重新提交',sales_self_review:'不能审核本人的提成单，请由另一位审核人处理',sales_reject_reason:'请填写退回原因',sales_search_minimum:'请输入至少 4 位订单号后点击搜索',sales_reference_duplicate:'这笔手动单号已经登记过',sales_amount:'计提金额不能为负数',sales_month_invalid:'请选择有效月份，不能申报未来月份',sales_buyer_required:'请填写微信号、旺旺号或微信昵称',sales_title:'请填写销售内容',sales_progress:'请选择订单进度'};
root.JUN_SALES={labels,eligible,money};if(typeof module!=='undefined')module.exports=root.JUN_SALES;if(typeof document==='undefined')return;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'});
let month=today().slice(0,7),filterMonth=new URLSearchParams(location.search).get('month')||'',data,tab='claims',busy=false,sequence=0,selected=new Set(),visibleCount=30,view='table';try{view=localStorage.getItem('jun-sales-view')||'table';}catch{}
async function api(path='',values){const r=await fetch('/api/customer/sales'+path,values?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)}:undefined);const d=await r.json();if(!r.ok)throw new Error(errors[d.error]||d.detail||d.error||'请求失败');return d;}
function message(text){$('#sales-message')?.remove();const e=document.createElement('div');e.id='sales-message';e.className='alert alert-danger';e.textContent=text;$('#module-content').before(e);}
function modal(title,body){const d=document.createElement('dialog');d.className='sales-dialog';d.innerHTML=`<header><strong>${esc(title)}</strong><button class="btn btn-icon btn-ghost-secondary" type="button" data-close aria-label="关闭">×</button></header><div class="sales-body">${body}</div>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.showModal();return d;}
function orderText(o){return `${o.id} · ${o.trade_status||'状态未提供'} / ${o.process_status||''} · ¥${money(o.amount)}`;}
function buyerText(value){if(value&&typeof value==='object')return String(value.account||value.name||'');const text=String(value||'');if(text.trim().startsWith('{')){try{return buyerText(JSON.parse(text));}catch{return '';}}return text;}
function orderPreview(o){const buyer=buyerText(o.buyer),date=v=>v?String(v).replace('T',' ').slice(5,16):'—';return `<article class="sales-order-preview"><div class="sales-order-heading"><span class="sales-chip ${o.received?'approved':'pending'}">${esc(o.trade_status||'状态未提供')}</span><span class="sales-hint">${esc(o.process_status||'')}</span></div><div class="sales-order-id"><span>订单</span><strong>${esc(o.id)}</strong></div>${buyer?`<div class="sales-order-buyer">旺旺号 <strong>${esc(buyer)}</strong></div>`:''}<div class="sales-product-list">${(o.items||[]).map(i=>{const sku=i.sku||i.name||'商品',name=i.name&&i.name!==sku?i.name:'',src=/^https:\/\//i.test(i.image_url||'')?i.image_url:'';return `<article class="sales-product"><div class="sales-product-head">${src?`<img loading="lazy" src="${esc(src)}" alt="${esc(sku)}">`:'<span class="sales-product-placeholder" aria-label="暂无商品图片">暂无图片</span>'}<div class="sales-product-info"><div class="sales-product-title"><strong>${esc(sku)}</strong><span>× ${esc(i.qty??'—')}</span></div>${name?`<p>${esc(name)}</p>`:''}<p>${esc([i.color,i.size].filter(Boolean).join(' / ')||'规格未提供')}</p><div class="sales-product-price"><span>单价 ${i.unit_price==null?'—':'¥'+money(i.unit_price)}</span><strong>${i.amount==null?'—':'¥'+money(i.amount)}</strong></div></div></div></article>`;}).join('')}</div><div class="sales-order-progress">${[['付款',o.paid_at||(['已付款','交易成功','已完成','确认收货','已收货'].includes(o.trade_status)?'已确认':'')],['发货',o.shipped_at||(/已发货/.test(o.process_status||'')||o.received?'已确认':'')],['收货',o.received_date|| (o.received?'已确认':'')]].map(([label,v])=>`<div class="${v?'is-done':''}"><span>${v?'✓':'○'}</span><strong>${label}</strong><small>${v==='已确认'?v:v?esc(date(v)):'待'+label}</small></div>`).join('')}</div>${o.seller_memo?`<div class="sales-order-memo"><span>操作备注</span><p>${esc(o.seller_memo)}</p></div>`:''}<div class="sales-order-total"><span>订单金额</span><strong>¥${money(o.amount)}</strong></div></article>`;}
function selectable(c){return eligible(c)&&c.owner_id===data.user_id&&data.can_submit;}
function statusText(c){return c.settlement_status==='approved'?'已计提':c.settlement_status==='pending'?'待审核':c.eligible?'待申报':'待完善／待收货';}
function refs(c){return c.import_meta?.order_refs?.length?c.import_meta.order_refs:c.kind==='linked'?(c.orders||[]).map(o=>o.id):[c.manual_order_no||c.reference||''];}
function rowActions(c){return `<button class="btn btn-sm btn-outline-primary" data-detail="${c.id}" data-kind="claim">查看明细</button>${c.can_edit?`<button class="btn btn-sm btn-outline-secondary" data-edit="${c.id}">编辑</button>`:''}`;}
function rowCheck(c){if(c.batch_id)return '';return `<input type="checkbox" aria-label="选择 ${esc(c.buyer||c.title)}" data-select="${c.id}" ${selected.has(c.id)?'checked':''} ${selectable(c)?'':'disabled'}>`;}
function claimCard(c){return `<article class="sales-card sales-record ${c.settlement_status==='approved'?'is-settled':''}"><header><h3>${rowCheck(c)} ${esc(buyerText(c.buyer)||'客户未填写')}</h3><span class="sales-chip ${c.settlement_status==='approved'?'approved':'pending'}">${statusText(c)}</span></header><div class="sales-record-refs">${refs(c).map(r=>`<div>${esc(r)}</div>`).join('')}</div><p class="sales-record-title">${esc(c.title)}</p><div class="sales-record-money"><div><span>计提金额</span><strong>¥${money(c.claim_amount)}</strong></div><div><span>提成 · 5%</span><strong>¥${money(c.commission)}</strong></div></div><div class="sales-meta"><span>计提月份 ${esc(c.settlement_month||'未申报')}</span>${data.can_approve?`<span>${esc(c.owner_name||'')}</span>`:''}<span>截图 ${(c.attachments||[]).length} 张</span></div>${!c.batch_id&&c.progress==='已收货'&&!c.received_date&&c.kind==='manual'?'<p class="sales-hint">已收货，申报前请补充确认收货日期。</p>':''}<div class="sales-actions">${rowActions(c)}</div></article>`;}
function salesTable(rows){return `<div class="table-responsive sales-record-table"><table class="table table-vcenter"><thead><tr><th>选择</th><th>客户／订单</th><th>销售内容</th><th>计提金额</th><th>提成 · 5%</th><th>状态</th><th>计提月份</th>${data.can_approve?'<th>登记人</th>':''}<th>操作</th></tr></thead><tbody>${rows.map(c=>`<tr class="${c.settlement_status==='approved'?'is-settled':''}"><td>${rowCheck(c)}</td><td><strong>${esc(buyerText(c.buyer)||'客户未填写')}</strong><div class="sales-record-refs">${refs(c).map(r=>`<div>${esc(r)}</div>`).join('')}</div></td><td><div class="sales-record-title">${esc(c.title)}</div></td><td class="sales-number">¥${money(c.claim_amount)}</td><td class="sales-number"><strong>¥${money(c.commission)}</strong></td><td><span class="sales-chip ${c.settlement_status==='approved'?'approved':'pending'}">${statusText(c)}</span></td><td>${esc(c.settlement_month||'未申报')}</td>${data.can_approve?`<td>${esc(c.owner_name||'')}</td>`:''}<td><div class="sales-actions">${rowActions(c)}</div></td></tr>`).join('')}</tbody></table></div>`;}
function render(){
 const closed=data.closed_months.includes(month),chosen=data.claims.filter(c=>selected.has(c.id)&&selectable(c));
 const filtered=data.claims.filter(c=>!filterMonth||!c.batch_id||c.settlement_month===filterMonth),rows=filtered.slice(0,visibleCount),settled=filtered.filter(c=>c.settlement_status==='approved');
 $('#module-toolbar').innerHTML=`<div class="sales-toolbar"><div class="sales-actions"><button class="btn ${tab==='claims'?'btn-primary':'btn-outline-primary'}" data-tab="claims">销售记录</button><button class="btn ${tab==='months'?'btn-primary':'btn-outline-primary'}" data-tab="months">月度提成与审核</button></div><label>计提月份 <select id="sales-filter-month" class="form-select"><option value="">全部月份</option>${[...new Set([today().slice(0,7),...(data.available_months||[]),filterMonth].filter(Boolean))].sort().reverse().map(m=>`<option value="${esc(m)}" ${m===filterMonth?'selected':''}>${esc(m)}</option>`).join('')}</select></label>${tab==='claims'?`<div class="sales-view-toggle" aria-label="显示方式"><button class="btn ${view==='table'?'btn-primary':'btn-outline-secondary'}" data-view="table" aria-pressed="${view==='table'}">表格</button><button class="btn ${view==='cards'?'btn-primary':'btn-outline-secondary'}" data-view="cards" aria-pressed="${view==='cards'}">卡片</button></div>`:''}${data.can_submit?'<button class="btn btn-primary" data-new>＋ 登记销售</button>':''}<button class="btn btn-outline-secondary" data-refresh>刷新</button></div>`;
 if(tab==='claims')$('#module-content').innerHTML=`<p class="sales-hint">默认显示全部月份，未计提在前、已计提在后，各组内新的在前。按计提月份筛选时，未申报订单仍会显示，方便跨月申报。</p><div class="sales-summary"><span>共 <strong>${filtered.length}</strong> 笔</span><span>未申报 <strong>${filtered.filter(c=>!c.batch_id).length}</strong> 笔</span><span>已计提 <strong>${settled.length}</strong> 笔</span><span>已计提提成 <strong>¥${money(settled.reduce((v,c)=>v+Number(c.commission),0))}</strong></span></div>${data.can_submit?`<details class="sales-submission" ${chosen.length?'open':''}><summary>本月申报 · 已选 ${chosen.length} 笔</summary><div class="sales-toolbar mt-2"><label>申报月份 <input id="sales-submit-month" type="month" class="form-control" value="${esc(month)}" max="${today().slice(0,7)}"></label><strong>提成 ¥${money(chosen.reduce((sum,c)=>sum+Number(c.commission),0))}</strong><button class="btn btn-primary" data-submit ${closed||!chosen.length?'disabled':''}>提交月度提成</button></div><p class="sales-hint">${closed?'该月份已提交或定稿，请选择其他月份。':'勾选本人已收货订单后提交，每月审核一次；批准后定稿。'}</p></details>`:''}<div class="sales-records" data-view="${view}"><div class="sales-record-cards">${rows.map(claimCard).join('')}</div>${salesTable(rows)}</div>${!filtered.length?'<div class="sales-empty">暂无销售记录。</div>':''}${filtered.length>visibleCount?`<div class="sales-more"><button class="btn btn-outline-primary" data-more>继续显示（已显示 ${rows.length} / ${filtered.length} 笔）</button></div>`:''}`;
 else $('#module-content').innerHTML=`<p class="sales-hint">每人每月一份提成单。待审核时可编辑订单，修改自动留痕；已计提月份已经定稿。</p>${data.batches.map(b=>`<article class="sales-card"><header><h3>${esc(b.month)} · ${esc(b.owner_name)}</h3><span class="sales-chip ${b.status}">${b.status==='approved'?'已计提 · 月份已定稿':labels[b.status]}</span></header><div class="sales-meta"><span>${b.items.length} 笔</span><span>计提金额 ¥${money(b.amount)}</span><strong>提成 ¥${money(b.commission)}</strong></div>${b.reason?`<p class="sales-note">${esc(b.reason)}</p>`:''}<div class="sales-actions"><button class="btn btn-outline-primary" data-detail="${b.id}" data-kind="batch">明细与截图</button>${b.status==='pending'&&b.owner_id===data.user_id&&data.can_submit?`<button class="btn btn-outline-secondary" data-action="withdraw" data-id="${b.id}">撤回修改</button>`:''}${b.status==='pending'&&b.owner_id!==data.user_id&&data.can_approve?`<button class="btn btn-success" data-action="approve" data-id="${b.id}">批准并定稿</button><button class="btn btn-outline-danger" data-action="reject" data-id="${b.id}">退回修改</button>`:''}</div></article>`).join('')||'<div class="sales-empty">暂无提成单。</div>'}`;
}
async function load(){const seq=++sequence,result=await api('?month='+encodeURIComponent(filterMonth));if(seq!==sequence)return;data=result;selected=new Set([...selected].filter(id=>data.claims.some(c=>c.id===id&&selectable(c))));render();}
async function mutate(action,values){if(busy)return;busy=true;try{await api('',{action,values});await load();return true;}catch(e){message(e.message);return false;}finally{busy=false;}}
async function compress(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('请选择 JPG、PNG 或 WebP 图片');const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>40000000)throw new Error('图片像素过大，请拆成多张截图以保持文字清晰');const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);const blob=await new Promise(r=>canvas.toBlob(r,'image/webp',.85));const best=blob&&blob.size<file.size?blob:file;if(best.size>12582912)throw new Error('压缩后仍超过 12 MB，请拆分截图');return best;}finally{bitmap.close();}}
function editor(c){
 let orders=[...(c?.orders||[])],attachments=[...(c?.attachments||[])];
 const d=modal(c?'编辑销售':'登记企业微信销售',`<form id="sales-edit"><div class="sales-fields"><label class="wide">订单类型<select class="form-select" name="kind"><option value="linked">关联系统订单</option><option value="manual">手动输入订单</option></select></label><div class="wide" id="linked-area"><div class="sales-search"><input class="form-control" id="order-query" placeholder="输入订单号，点击搜索才会查询" minlength="4" maxlength="100"><button type="button" class="btn btn-outline-primary" id="order-search">搜索</button></div><div id="order-results"></div><div id="order-selected"></div></div><label class="wide"><span id="buyer-label">旺旺号（可补全）</span><input class="form-control" name="buyer" required maxlength="100" value="${esc(buyerText(c?.buyer))}"></label><div id="manual-number" class="wide"><span>手动订单号</span><p class="sales-hint">${esc(c?.manual_order_no||'保存后自动生成，无需填写')}</p></div><label class="wide" id="manual-title">款式／款号／销售内容<input class="form-control" name="title" maxlength="300" value="${esc(c?.title)}"></label><label id="manual-amount">订单金额<input class="form-control" name="amount" type="number" min="0" step=".01" value="${esc(c?.amount??0)}"></label><label id="manual-progress">订单进度<select class="form-select" name="progress"><option>未发货</option><option>已发货</option><option>已收货</option></select></label><label id="manual-received">确认收货日期<input class="form-control" name="received_date" type="date" max="${today()}" value="${esc(c?.received_date||'')}"></label><label id="manual-adjustment">退款／补款调整（选填，减少填负数）<input class="form-control" name="adjustment" type="number" step=".01" value="${esc(c?.adjustment??0)}"></label><label id="manual-adjustment-reason">调整原因<input class="form-control" name="adjustment_reason" maxlength="1000" value="${esc(c?.adjustment_reason)}"></label><div class="wide"><label>聊天截图 <span class="sales-hint">必填 · 最多 12 张</span><span class="sales-upload"><span>＋ 选择聊天截图</span><input name="images" type="file" aria-label="选择聊天截图" accept="image/png,image/jpeg,image/webp" multiple></span></label><p class="sales-hint">自动压缩，保留文字清晰度。原有 ${attachments.length} 张；新增图片保存时上传。</p><div id="local-previews" class="sales-images"></div><div id="saved-images"></div></div><label class="wide">备注（选填）<textarea class="form-control" name="note" maxlength="2000">${esc(c?.note)}</textarea></label></div><div class="sales-error" id="edit-error" role="alert"></div><footer><button class="btn btn-primary" type="submit">保存登记</button></footer></form>`);
 d.classList.add('sales-editor');const form=d.querySelector('form'),el=form.elements;el.kind.value=c?.kind||'linked';el.progress.value=c?.progress||'未发货';let uploads=[],localUrls=[];let buyerEdited=Boolean(c?.buyer&&c.buyer!==[...new Set(orders.map(o=>buyerText(o.buyer)).filter(Boolean))].join(' / '));el.buyer.oninput=()=>{buyerEdited=true;};
 const showOrders=()=>{d.querySelector('#order-selected').innerHTML=orders.map(o=>`<div class="sales-order">${orderPreview(o)}<div class="sales-order-action"><span class="sales-linked">✓ 已关联</span><button type="button" class="btn btn-outline-secondary" data-remove-order="${esc(o.id)}">移除关联</button></div></div>`).join('');if(el.kind.value==='linked'){if(!buyerEdited)el.buyer.value=[...new Set(orders.map(o=>buyerText(o.buyer)).filter(Boolean))].join(' / ');el.amount.value=orders.reduce((sum,o)=>sum+Number(o.amount||0),0).toFixed(2);el.title.value=orders.map(o=>o.title||(o.items||[]).map(i=>[i.sku,i.name].filter(Boolean).join(' ')).join('、')||o.id).join('；').slice(0,300);}};
 function sync(){const linked=el.kind.value==='linked';d.querySelector('#linked-area').hidden=!linked;for(const id of ['manual-number','manual-title','manual-amount','manual-progress','manual-received','manual-adjustment','manual-adjustment-reason'])d.querySelector('#'+id).hidden=linked;d.querySelector('#buyer-label').textContent=linked?'旺旺号（自动带入，可补全）':'微信号／旺旺号／微信昵称';el.amount.readOnly=linked;el.title.readOnly=linked;el.title.required=!linked;el.amount.required=!linked;el.received_date.required=!linked&&el.progress.value==='已收货';el.adjustment_reason.required=!linked&&Number(el.adjustment.value)!==0;showOrders();}
 el.kind.onchange=sync;el.progress.onchange=sync;el.adjustment.oninput=sync;sync();
 async function savedImages(){if(!c)return;try{const detail=await api('/detail?id='+c.id+'&kind=claim');d.querySelector('#saved-images').innerHTML=attachments.map(p=>`<div class="sales-images"><a href="${esc(imageUrl(detail.urls[p]))}" target="_blank" rel="noopener"><img src="${esc(imageUrl(detail.urls[p]))}" alt="原有聊天截图"></a><button class="btn btn-sm" type="button" data-remove-image="${esc(p)}">移除</button></div>`).join('');}catch(e){d.querySelector('#edit-error').textContent=e.message;}}
 savedImages();
 el.images.onchange=()=>{uploads=[];localUrls.forEach(URL.revokeObjectURL);localUrls=[...el.images.files].map(f=>URL.createObjectURL(f));d.querySelector('#local-previews').innerHTML=localUrls.map(u=>`<img src="${u}" alt="待上传聊天截图">`).join('');};d.addEventListener('close',()=>localUrls.forEach(URL.revokeObjectURL));
 let searching=false;async function search(){if(searching)return;const q=d.querySelector('#order-query').value.trim();if(q.length<4){d.querySelector('#edit-error').textContent=errors.sales_search_minimum;return;}d.querySelector('#edit-error').textContent='';searching=true;d.querySelector('#order-search').disabled=true;try{const result=await api('?q='+encodeURIComponent(q));d.querySelector('#order-results').innerHTML=result.orders.map((o,i)=>`<div class="sales-order">${orderPreview(o)}<button type="button" class="btn btn-outline-primary sales-link-button" data-pick="${i}" ${o.claimed&&!orders.some(x=>x.id===o.id)&&!(o.claim_ids||[]).includes(c?.id)?'disabled':''}>${o.claimed&&!orders.some(x=>x.id===o.id)&&!(o.claim_ids||[]).includes(c?.id)?'已被认领':'关联此订单'}</button></div>`).join('')||'<p>当前采集未找到此订单。可核对单号，微信直接付款请选手动订单。</p>';d.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{const o=result.orders[Number(b.dataset.pick)];if(!orders.some(x=>x.id===o.id))orders.push(o);showOrders();d.querySelector('#order-results').innerHTML='';});}catch(e){d.querySelector('#edit-error').textContent=e.message;}finally{searching=false;d.querySelector('#order-search').disabled=false;}}
 d.querySelector('#order-search').onclick=search;d.querySelector('#order-query').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();search();}};
 d.addEventListener('click',e=>{const r=e.target.closest('[data-remove-order]');if(r){orders=orders.filter(o=>o.id!==r.dataset.removeOrder);showOrders();}const a=e.target.closest('[data-remove-image]');if(a){attachments=attachments.filter(p=>p!==a.dataset.removeImage);a.parentElement.remove();}});
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;try{const files=[...el.images.files];if(attachments.length+files.length<1||attachments.length+files.length>12)throw new Error(errors.sales_images_required);if(el.kind.value==='linked'&&!orders.length)throw new Error(errors.sales_order_required);
 for(let i=uploads.length;i<files.length;i++){button.textContent=`正在压缩上传 ${i+1}/${files.length}`;const blob=await compress(files[i]);const ticket=await api('/upload',{type:blob.type,size:blob.size});const {error}=await window.JUN_SUPABASE.storage.from(ticket.bucket).uploadToSignedUrl(ticket.path,ticket.token,blob,{contentType:blob.type});if(error)throw error;uploads.push(ticket.path);}
 const v=Object.fromEntries(new FormData(form));delete v.images;Object.assign(v,{id:c?.id,version:c?.version,order_ids:orders.map(o=>o.id),attachments:[...attachments,...uploads]});await api('',{action:'save',values:v});d.close();await load();}catch(e){d.querySelector('#edit-error').textContent=e.message;}finally{button.disabled=false;button.textContent='保存登记';}};
}
function imageUrl(url){if(!url)return '';const at=url.indexOf('/storage/v1/');if(at<0)return '';return window.JUN_CONFIG.supabaseUrl.replace(/\/$/,'')+url.slice(at);}
function evidence(c,urls){c={...c,claim_amount:c.claim_amount??(Number(c.amount||0)+Number(c.adjustment||0)),commission:c.commission??Math.round((Number(c.amount||0)+Number(c.adjustment||0))*5)/100};return `<h4>${esc(c.title)}</h4><p>${c.kind==='linked'?'关联订单':'手动输入订单'} · 计提金额 ¥${money(c.claim_amount)} · 提成 ¥${money(c.commission)}</p><p>${esc(buyerText(c.buyer))}${c.kind==='manual'?' · 单号 '+esc(c.manual_order_no||c.reference||'—'):''}</p>${c.import_meta?.order_refs?.length?`<div class="sales-record-refs">${c.import_meta.order_refs.map(x=>`<div>${esc(x)}</div>`).join('')}</div>`:''}${c.settlement_month?`<p>计提月份 ${esc(c.settlement_month)} · ${statusText(c)}</p>`:''}${c.import_meta?.receipt_text?.length?`<p class="sales-hint">原表收货状态：${esc(c.import_meta.receipt_text.join(' / '))}${!c.received_date?'；未提供具体收货日期':''}</p>`:''}${(c.orders||[]).map(orderPreview).join('')}<p class="sales-note">${esc(c.note)}${c.adjustment_reason?'\n调整 '+money(c.adjustment)+'：'+esc(c.adjustment_reason):''}</p><div class="sales-images">${(c.attachments||[]).map(p=>`<a href="${esc(imageUrl(urls[p]))}" target="_blank" rel="noopener"><img loading="lazy" src="${esc(imageUrl(urls[p]))}" alt="聊天截图，点击查看清晰图"></a>`).join('')}</div>`;}
function archiveEvidence(r,urls){const names={B:'旺旺号',C:'订单号',E:'金额',F:'确认收货',H:'付款方式／补充说明',I:'备注1',J:'备注2',K:'提成金额',L:'提成结算月'};return `<h3>原表第 ${r.source_row} 行 · ${esc(r.month||'结算月未填写')}</h3>${Object.entries(r.cells).filter(([a,c])=>c.v||c.f).map(([a,c])=>`<p class="sales-note"><strong>${esc(names[a.replace(/\d/g,'')]||a)}（${a}）</strong>：${esc(a.startsWith('L')&&r.month?r.month:c.v)}${c.f?`<small>　公式 ${esc(c.f)}</small>`:''}</p>`).join('')}<p class="sales-hint">相关合并单元格：${esc((r.merges||[]).join('、')||'无')}</p><div class="sales-images">${(r.attachments||[]).map(p=>`<a href="${esc(imageUrl(urls[p]))}" target="_blank" rel="noopener"><img loading="lazy" src="${esc(imageUrl(urls[p]))}" alt="原表截图"></a>`).join('')}</div>`;}
async function detail(id,kind){const d=modal('销售明细','正在读取…');try{const r=await api('/detail?id='+id+'&kind='+kind);const editable=kind==='batch'&&r.record.status==='pending'&&(data.can_approve||r.record.owner_id===data.user_id&&data.can_submit);d.querySelector('.sales-body').innerHTML=(kind==='archive'?archiveEvidence(r.record,r.urls):kind==='batch'?`<h3>${esc(r.record.month)} · ${labels[r.record.status]}</h3>${r.record.items.map(c=>evidence(c,r.urls)+(editable?`<button class="btn btn-sm" data-edit-pending="${c.id}">编辑订单</button>`:'')).join('<hr>')}`:evidence(r.record,r.urls)+(r.can_edit?`<button class="btn" data-edit-pending="${r.record.id}">编辑订单</button>`:''))+(data.can_approve?`<h3>修改与审批记录</h3>${r.history.map(h=>`<details class="sales-history"><summary>${esc(h.created_at)} · ${esc(h.actor_name)} · ${esc(({import:'批量导入',save:'保存登记',edit:'修改订单并更新月单',submit:'提交定稿',approve:'审核通过',reject:'退回修改',withdraw:'撤回'})[h.action]||h.action)}</summary>${h.payload.reason?`<p>${esc(h.payload.reason)}</p>`:''}${h.payload.before?'<h4>修改前</h4>'+evidence(h.payload.before,r.urls):''}${h.payload.after?'<h4>修改后</h4>'+evidence(h.payload.after,r.urls):''}${(h.payload.items||[]).map(c=>evidence(c,r.urls)).join('<hr>')}</details>`).join('')}`:'');}catch(e){d.querySelector('.sales-body').textContent=e.message;}}
async function editPending(id,dialog){try{const r=await api('/detail?id='+id+'&kind=claim');if(!r.can_edit)throw new Error('该订单已经定稿，不能修改');dialog?.close();editor(r.record);}catch(e){message(e.message);}}
function confirmAction(action,b){const d=modal(action==='submit'?'确认月度提成单':({approve:'批准并定稿',reject:'退回修改',withdraw:'撤回提成单'})[action],`<form><p>${action==='submit'?`${esc(month)}：确认本月订单已经选齐。提交后仍可编辑订单，修改自动留痕；批准后该月份不能再改动。`:action==='approve'?'批准后，这份月单及申报月份固定，后续新增订单需申报其他月份。':action==='withdraw'?'撤回后本月重新可编辑，原提交记录仍保留。':'填写需要修改的内容，申请人修改后重新提交。'}</p>${action==='reject'?'<textarea class="form-control" name="reason" required maxlength="1000" placeholder="退回原因"></textarea>':''}<footer><button class="btn btn-primary" type="submit">确认${action==='submit'?'提交':''}</button></footer></form>`);d.querySelector('form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('button');btn.disabled=true;const claims=data.claims.filter(c=>selected.has(c.id)&&selectable(c));const values=action==='submit'?{month,ids:claims.map(c=>c.id),expected:claims.map(c=>({id:c.id,version:c.version,amount:c.claim_amount,orders:c.orders}))}:{id:b.id,version:b.version,reason:new FormData(e.target).get('reason')||''};if(await mutate(action,values)){d.close();if(action==='submit'){selected.clear();tab='months';render();}}else {btn.disabled=false;let err=d.querySelector('.sales-error');if(!err){err=document.createElement('p');err.className='sales-error';d.querySelector('form').prepend(err);}err.textContent=$('#sales-message')?.textContent||'提交失败，请重试';}};}
document.addEventListener('change',e=>{if(e.target.id==='sales-filter-month'){filterMonth=e.target.value;visibleCount=30;const u=new URL(location);filterMonth?u.searchParams.set('month',filterMonth):u.searchParams.delete('month');history.replaceState(null,'',u);load().catch(e=>message(e.message));}if(e.target.id==='sales-submit-month'){month=e.target.value;render();}if(e.target.matches('[data-select]')){e.target.checked?selected.add(e.target.dataset.select):selected.delete(e.target.dataset.select);render();}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){tab=b.dataset.tab;render();}if(b.dataset.view){view=b.dataset.view;try{localStorage.setItem('jun-sales-view',view);}catch{}render();}if(b.hasAttribute('data-more')){visibleCount+=30;render();}if(b.hasAttribute('data-new'))editor();if(b.dataset.editPending)editPending(b.dataset.editPending,b.closest('dialog'));if(b.dataset.edit)editor(data.claims.find(c=>c.id===b.dataset.edit));if(b.dataset.detail)detail(b.dataset.detail,b.dataset.kind);if(b.hasAttribute('data-refresh'))load().catch(e=>message(e.message));if(b.hasAttribute('data-submit'))confirmAction('submit');if(b.dataset.action)confirmAction(b.dataset.action,data.batches.find(x=>x.id===b.dataset.id));});
Promise.resolve(window.JUN_AUTH_READY).then(load).catch(e=>message(e.message));
})(typeof window!=='undefined'?window:globalThis);
