(function(root){
'use strict';
const labels={pending:'待审核',approved:'已通过 · 已计入工资',rejected:'已退回',withdrawn:'已撤回'};
const money=n=>Number(n??0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const eligible=c=>c.eligible===true && !c.batch_id;
const errors={sales_request_failed:'服务暂时异常，请稍后重试',sales_order_not_successful:'所有关联订单都必须为“交易成功”才能提交结算。已提交的记录如需关联其他状态的订单，请先撤回结算。',sales_forbidden:'没有这项操作权限',sales_locked:'订单已被提交或不属于本人，请刷新',sales_version:'记录已更新，请刷新后重试',sales_month_closed:'该月份已经提交或定稿，不能再次申报',sales_not_received:'选中的订单尚未确认收货，或采集暂时没有这笔订单',sales_system_receipt_only:'关联系统的订单只能使用系统确认收货时间',sales_image_batch:'图片批次无效，请刷新重试',sales_received_required:'请先填写确认收货日期，再选择结算月提交审核',sales_payroll_locked:'该月份工资已发放，请选择其他结算月',sales_use_settlement_month:'请在订单上选择结算月提交审核',sales_legacy_month:'请先撤回原月单，再逐单选择结算月',sales_received_future:'收货日期不能晚于今天',sales_select_orders:'请先选择要申报的订单',sales_images_required:'请提供 1–12 张聊天截图',sales_image_invalid:'图片尚未上传成功或格式、大小不符合要求',sales_order_required:'请关联至少一笔订单',sales_order_missing:'当前采集未找到该订单，请重新搜索',sales_order_claimed:'这笔订单已被认领，不能重复登记',sales_adjustment_reason:'调整金额时请填写退款、差价或补款原因',sales_source_changed:'订单或金额已更新，请刷新核对后重新提交',sales_self_review:'不能审核本人的提成单，请由另一位审核人处理',sales_reject_reason:'请填写退回原因',sales_search_minimum:'请输入至少 4 位订单号后点击搜索',sales_reference_duplicate:'这笔手动单号已经登记过',sales_amount:'计提金额不能为负数',sales_month_invalid:'结算月只能选择上个月或本月',sales_buyer_required:'请填写微信号、旺旺号或微信昵称',sales_title:'请填写销售内容',sales_progress:'请选择订单进度'};
const linkedOrdersSucceeded=orders=>Boolean(orders?.length)&&orders.every(o=>o.trade_status==='交易成功');
const pendingLinkedNotSuccessful=(c,kind,orders)=>Boolean(c?.batch_id&&c.settlement_status==='pending'&&kind==='linked'&&!linkedOrdersSucceeded(orders));
const completionText=c=>c.kind==='linked'?(linkedOrdersSucceeded(c.orders)?'交易成功':'待交易成功'):(c.received_date||'收货日期未填写');
const saleValues=(values,c,orders,attachments,withdraw=false)=>{const v={...values,id:c?.id,version:c?.version,attachments};delete v.images;if(v.kind==='linked'){for(const k of ['title','amount','progress','received_date','adjustment','adjustment_reason','reference'])delete v[k];v.order_ids=orders.map(o=>o.id);}else v.order_ids=[];if(withdraw)v.withdraw_settlement=true;return v;};
const previousMonth=date=>{const [y,m]=date.slice(0,7).split('-').map(Number);return `${m===1?y-1:y}-${String(m===1?12:m-1).padStart(2,'0')}`;};
const settlementMonths=date=>[previousMonth(date),date.slice(0,7)];
const settlementLabels={unsubmitted:'未提交',pending:'已提交未审核',approved:'已提交'};
const settlementState=c=>c.settlement_status==='approved'?'approved':c.settlement_status==='pending'?'pending':'unsubmitted';
const normalizeSettlementFilter=value=>Object.hasOwn(settlementLabels,value)?value:'';
const filterClaims=(claims,month,status)=>claims.filter(c=>(!month||!c.batch_id||c.settlement_month===month)&&(!normalizeSettlementFilter(status)||settlementState(c)===status));
const statusText=c=>settlementLabels[settlementState(c)];
const reviewPending=c=>settlementState(c)==='pending';
const sumMoney=(rows,key)=>rows.reduce((v,c)=>v+Math.round(Number(c[key]||0)*100),0)/100;
const monthTotals=(claims,month)=>{const rows=claims.filter(c=>!month||c.settlement_month===month),approved=rows.filter(c=>c.settlement_status==='approved');return {count:rows.length,amount:sumMoney(rows,'claim_amount'),commission:sumMoney(rows,'commission'),pending:rows.filter(reviewPending).length,approvedAmount:sumMoney(approved,'claim_amount'),approvedCommission:sumMoney(approved,'commission')};};
root.JUN_SALES={linkedOrdersSucceeded,completionText,pendingLinkedNotSuccessful,saleValues,labels,eligible,money,previousMonth,monthTotals,reviewPending,settlementMonths,settlementState,settlementLabels,normalizeSettlementFilter,filterClaims,statusText};if(typeof module!=='undefined')module.exports=root.JUN_SALES;if(typeof document==='undefined')return;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'});
let month=today().slice(0,7),filterMonth=new URLSearchParams(location.search).get('month')||'',data,filterStatus=normalizeSettlementFilter(new URLSearchParams(location.search).get('settlement')),busy=false,sequence=0,selected=new Set(),visibleCount=30,view=window.matchMedia('(max-width:760px)').matches?'cards':'table';try{view=localStorage.getItem('jun-sales-view')||view;}catch{}
async function api(path='',values,options={}){
 const controller=new AbortController(),abort=()=>controller.abort();let timedOut=false;
 if(options.signal?.aborted)controller.abort();else options.signal?.addEventListener('abort',abort,{once:true});
 const timer=options.timeout?setTimeout(()=>{timedOut=true;controller.abort();},options.timeout):null;
 let cancelled;const interruption=new Promise((_,reject)=>{cancelled=()=>reject(Object.assign(new Error('请求已取消'),{name:'AbortError'}));if(controller.signal.aborted)cancelled();else controller.signal.addEventListener('abort',cancelled,{once:true});});
 try{const r=await Promise.race([fetch('/api/customer/sales'+path,{...(values?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)}:{}),signal:controller.signal}),interruption]);
 const d=await r.json();if(!r.ok)throw new Error(errors[d.error]||d.detail||'请求失败，请稍后重试');return d;
 }catch(e){if(timedOut)throw new Error('请求超时，请重试');throw e;}finally{if(timer)clearTimeout(timer);controller.signal.removeEventListener('abort',cancelled);options.signal?.removeEventListener('abort',abort);}
}
function message(text){$('#sales-message')?.remove();const e=document.createElement('div');e.id='sales-message';e.className='alert alert-danger';e.textContent=text;$('#module-content').before(e);}
function modal(title,body){const d=document.createElement('dialog');d.className='sales-dialog';d.innerHTML=`<header><strong>${esc(title)}</strong><button class="btn btn-icon btn-ghost-secondary" type="button" data-close aria-label="关闭">×</button></header><div class="sales-body">${body}</div>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.showModal();return d;}
function orderText(o){return `${o.id} · ${o.trade_status||'状态未提供'} / ${o.process_status||''} · ¥${money(o.amount)}`;}
function buyerText(value){if(value&&typeof value==='object')return String(value.account||value.name||'');const text=String(value||'');if(text.trim().startsWith('{')){try{return buyerText(JSON.parse(text));}catch{return '';}}return text;}
function orderPreview(o){const buyer=buyerText(o.buyer),date=v=>v?String(v).replace('T',' ').slice(5,16):'—';return `<article class="sales-order-preview"><div class="sales-order-heading"><span class="sales-chip ${o.trade_status==='交易成功'?'approved':'pending'}">${esc(o.trade_status||'状态未提供')}</span><span class="sales-hint">${esc(o.process_status||'')}</span></div><div class="sales-order-id"><span>订单</span><strong>${esc(o.id)}</strong></div>${buyer?`<div class="sales-order-buyer">旺旺号 <strong>${esc(buyer)}</strong></div>`:''}<div class="sales-product-list">${(o.items||[]).map(i=>{const sku=i.sku||i.name||'商品',name=i.name&&i.name!==sku?i.name:'',src=/^https:\/\//i.test(i.image_url||'')?i.image_url:'';return `<article class="sales-product"><div class="sales-product-head">${src?`<img loading="lazy" src="${esc(src)}" alt="${esc(sku)}">`:'<span class="sales-product-placeholder" aria-label="暂无商品图片">暂无图片</span>'}<div class="sales-product-info"><div class="sales-product-title"><strong>${esc(sku)}</strong><span>× ${esc(i.qty??'—')}</span></div>${name?`<p>${esc(name)}</p>`:''}<p>${esc([i.color,i.size].filter(Boolean).join(' / ')||'规格未提供')}</p><div class="sales-product-price"><span>单价 ${i.unit_price==null?'—':'¥'+money(i.unit_price)}</span><strong>${i.amount==null?'—':'¥'+money(i.amount)}</strong></div></div></div></article>`;}).join('')}</div><div class="sales-order-progress">${[['付款',o.paid_at||(['已付款','交易成功','已完成','确认收货','已收货'].includes(o.trade_status)?'已确认':'')],['发货',o.shipped_at||(/已发货/.test(o.process_status||'')||o.received?'已确认':'')],['完成',o.trade_status==='交易成功'?'已确认':'']].map(([label,v])=>`<div class="${v?'is-done':''}"><span>${v?'✓':'○'}</span><strong>${label}</strong><small>${v.startsWith?.('已确认')?v:v?esc(date(v)):'待'+label}</small></div>`).join('')}</div>${o.seller_memo?`<div class="sales-order-memo"><span>操作备注</span><p>${esc(o.seller_memo)}</p></div>`:''}<div class="sales-order-total"><span>订单金额</span><strong>¥${money(o.amount)}</strong></div></article>`;}
function settlementOptions(value=''){const months=settlementMonths(today()),selected=months.includes(value)?value:months[0];return months.map(m=>`<option value="${m}" ${m===selected?'selected':''} ${(data.payroll_locked_months||[]).includes(m)?'disabled':''}>${m}${(data.payroll_locked_months||[]).includes(m)?'（工资已发放）':''}</option>`).join('');}

function refs(c){return c.import_meta?.order_refs?.length?c.import_meta.order_refs:c.kind==='linked'?(c.orders||[]).map(o=>o.id):[c.manual_order_no||c.reference||''];}
function canSettle(c){return (data.can_approve||c.owner_id===data.user_id&&data.can_submit)&&c.settlement_status!=='approved';}
function editAction(c){const enabled=c.can_edit&&c.settlement_status!=='approved',hint=enabled?'修改':c.settlement_status==='approved'?'已审核通过，不可修改':'仅登记人或管理员可修改';return `<button type="button" class="btn btn-sm btn-icon btn-outline-primary sales-edit-button" ${enabled?`data-edit="${c.id}"`:'disabled'} title="${hint}" aria-label="修改"><i class="ti ti-edit" aria-hidden="true"></i></button>`;}
function rowActions(c){const b=data.batches.find(x=>x.id===c.batch_id);return `${canSettle(c)?`<button type="button" class="btn btn-sm btn-outline-primary" data-settlement="${c.id}"><i class="ti ti-calendar me-1" aria-hidden="true"></i>选择结算月</button>`:`<button type="button" class="btn btn-sm btn-outline-primary" disabled title="${c.settlement_status==='approved'?'已审核通过，不可更改结算月':'仅登记人或管理员可选择结算月'}"><i class="ti ti-calendar me-1" aria-hidden="true"></i>选择结算月</button>`}${b?.status==='pending'&&c.owner_id===data.user_id?`<button class="btn btn-sm btn-outline-secondary" data-action="withdraw" data-id="${b.id}">撤回</button>`:''}${b?.status==='pending'&&data.can_approve&&c.owner_id!==data.user_id?`<button class="btn btn-sm btn-success" data-action="approve" data-id="${b.id}">审核通过</button><button class="btn btn-sm btn-outline-danger" data-action="reject" data-id="${b.id}">退回</button>`:''}${c.admin_review_pending&&!c.batch_id?'<span class="sales-hint">选择结算月后审核</span>':''}${c.settlement_status==='approved'?'<span class="sales-hint">已通过</span>':''}`;}
const photoCache=new Map(),originalPhotoCache=new Map(),evidenceRequests=new Set();let photoTimer;
const photoObserver=typeof IntersectionObserver==='undefined'?null:new IntersectionObserver(entries=>{
 for(const entry of entries)if(entry.isIntersecting){entry.target.dataset.photoReady='1';photoObserver.unobserve(entry.target);}
 clearTimeout(photoTimer);photoTimer=setTimeout(()=>loadPhotos(data.claims),40);
},{rootMargin:'160px'});
function thumbnails(c){return `<div class="sales-thumbnails">${(c.attachments||[]).map((p,i)=>`<button type="button" class="sales-thumb" data-photo="${esc(p)}" aria-label="放大查看截图 ${i+1}"><img loading="lazy" decoding="async" width="240" height="320" alt="截图 ${i+1}"><span>加载中</span></button>`).join('')||'<span class="sales-hint">暂无截图</span>'}</div>`;}
function photoHint(b,text){let hint=b.querySelector('span');if(!hint){hint=document.createElement('span');b.append(hint);}hint.textContent=text;}
function paintPhotos(){document.querySelectorAll('[data-photo]').forEach(b=>{
 if(!b.dataset.photoReady)return;const c=photoCache.get(b.dataset.photo);if(!c||c.until<=Date.now())return;
 const img=b.querySelector('img');if(img.getAttribute('src')===c.url)return;
 photoHint(b,'加载中');img.onload=()=>{delete b.dataset.photoError;b.querySelector('span')?.remove();};
 img.onerror=()=>{photoCache.delete(b.dataset.photo);b.dataset.photoError='1';photoHint(b,'点击重试');};img.src=c.url;
});}
async function loadPhotos(rows){
 const wanted=new Set();document.querySelectorAll('[data-photo]').forEach(b=>{if(!b.dataset.photoReady){if(photoObserver)photoObserver.observe(b);else b.dataset.photoReady='1';}if(b.dataset.photoReady&&!b.dataset.photoError)wanted.add(b.dataset.photo);});
 paintPhotos();const owners=new Map();for(const c of rows)for(const p of c.attachments||[])if(wanted.has(p))owners.set(p,c.id);
 const missing=[...owners.keys()].filter(p=>(!photoCache.has(p)||photoCache.get(p).until<=Date.now())&&!evidenceRequests.has(p));
 missing.forEach(p=>evidenceRequests.add(p));
 for(let i=0;i<missing.length;i+=12){const paths=missing.slice(i,i+12);try{
 const r=await api('/images',{ids:[...new Set(paths.map(p=>owners.get(p)))],paths,variant:'thumbnail'},{timeout:20000});
 for(const [p,u] of Object.entries(r.urls||{})){const url=imageUrl(u);if(url)photoCache.set(p,{url,until:Date.now()+3000000});}
 for(const p of r.missing||[])document.querySelectorAll('[data-photo]').forEach(b=>{if(b.dataset.photo===p){b.dataset.photoError='1';photoHint(b,'点击重试');}});paintPhotos();
 }catch(e){document.querySelectorAll('[data-photo]').forEach(b=>{if(paths.includes(b.dataset.photo)){b.dataset.photoError='1';photoHint(b,'点击重试');}});}finally{paths.forEach(p=>evidenceRequests.delete(p));}}
}
async function viewPhoto(path){
 const d=modal('聊天截图','<p data-photo-status>正在加载原图…</p><button type="button" class="btn btn-outline-primary" data-photo-retry hidden>重新加载</button><button type="button" class="btn btn-outline-primary" data-zoom-photo>原尺寸</button><div class="sales-photo-stage"><img alt="聊天截图，点击放大"></div>');d.classList.add('sales-photo-viewer');
 const img=d.querySelector('img'),status=d.querySelector('[data-photo-status]'),retry=d.querySelector('[data-photo-retry]');
 const loadOriginal=async()=>{retry.hidden=true;status.textContent='正在加载原图…';try{let cached=originalPhotoCache.get(path);
 if(!cached||cached.until<=Date.now()){const claim=data.claims.find(c=>(c.attachments||[]).includes(path));if(!claim)throw new Error('记录已更新，请刷新后查看');const r=await api('/images',{ids:[claim.id],paths:[path]},{timeout:20000});const url=imageUrl(r.urls?.[path]);if(!url)throw new Error('图片不存在或暂时不可用');cached={url,until:Date.now()+3000000};originalPhotoCache.set(path,cached);}
 img.onload=()=>{status.textContent='点击图片切换原尺寸，可滚动查看文字。';};img.onerror=()=>{originalPhotoCache.delete(path);status.textContent='图片加载失败，请重试';retry.hidden=false;};img.src=cached.url;
 }catch(e){status.textContent=e.message;retry.hidden=false;}};
 retry.onclick=loadOriginal;const toggle=()=>{d.classList.toggle('is-original');d.querySelector('[data-zoom-photo]').textContent=d.classList.contains('is-original')?'适应窗口':'原尺寸';};d.querySelector('[data-zoom-photo]').onclick=toggle;img.onclick=toggle;await loadOriginal();
}
function recordClass(c){return reviewPending(c)?'is-pending':c.settlement_status==='approved'?'is-settled':'';}
function claimCard(c){return `<article class="sales-card sales-record ${recordClass(c)}"><header class="sales-card-head"><div><h3>${esc(buyerText(c.buyer)||'客户未填写')}</h3><span class="sales-chip ${settlementState(c)}" title="${settlementState(c)==='approved'?'已提交结算并审核通过':statusText(c)}">${statusText(c)}</span></div><div class="sales-card-actions">${editAction(c)}<div class="sales-actions">${rowActions(c)}</div></div></header><div class="sales-record-refs">${refs(c).map(r=>`<div>${esc(r)}</div>`).join('')}</div><p class="sales-record-title">${esc(c.title)}</p>${thumbnails(c)}<div class="sales-record-money"><div><span>销售额</span><strong>¥${money(c.claim_amount)}</strong></div><div><span>提成 · 5%</span><strong>¥${money(c.commission)}</strong></div></div><div class="sales-meta"><span>结算月 ${esc(c.settlement_month||'未选择')}</span><span>完成情况 ${esc(completionText(c))}</span>${data.can_approve?`<span>${esc(c.owner_name||'')}</span>`:''}</div></article>`;}
function salesTable(rows){return `<div class="table-responsive sales-record-table"><table class="table table-vcenter"><thead><tr><th class="sales-edit-cell" title="修改" aria-label="修改"><i class="ti ti-edit" aria-hidden="true"></i></th><th class="sales-operation-cell">结算操作</th><th>客户／订单</th><th>销售内容</th><th>截图</th><th>销售额</th><th>提成 · 5%</th><th>状态</th><th>结算月</th><th>完成情况</th>${data.can_approve?'<th>登记人</th>':''}</tr></thead><tbody>${rows.map(c=>`<tr class="${recordClass(c)}"><td class="sales-edit-cell">${editAction(c)}</td><td class="sales-operation-cell"><div class="sales-actions">${rowActions(c)}</div></td><td><strong>${esc(buyerText(c.buyer)||'客户未填写')}</strong><div class="sales-record-refs">${refs(c).map(r=>`<div>${esc(r)}</div>`).join('')}</div></td><td><div class="sales-record-title">${esc(c.title)}</div></td><td>${thumbnails(c)}</td><td class="sales-number">¥${money(c.claim_amount)}</td><td class="sales-number"><strong>¥${money(c.commission)}</strong></td><td><span class="sales-chip ${settlementState(c)}" title="${settlementState(c)==='approved'?'已提交结算并审核通过':statusText(c)}">${statusText(c)}</span></td><td>${esc(c.settlement_month||'未选择')}</td><td>${esc(completionText(c))}</td>${data.can_approve?`<td>${esc(c.owner_name||'')}</td>`:''}</tr>`).join('')}</tbody></table></div>`;}
function render(){
 photoObserver?.disconnect();
 const filtered=filterClaims(data.claims,filterMonth,filterStatus),rows=filtered.slice(0,visibleCount),totals=monthTotals(data.claims,filterMonth);
 const months=new Set([previousMonth(today()),today().slice(0,7),...(data.available_months||[]),filterMonth]);
 $('#module-toolbar').innerHTML=`<div class="sales-toolbar"><label>结算状态 <select id="sales-filter-status" class="form-select"><option value="">全部状态</option>${Object.entries(settlementLabels).map(([value,label])=>`<option value="${value}" ${value===filterStatus?'selected':''}>${label}</option>`).join('')}</select></label><label>统计月份 <select id="sales-filter-month" class="form-select"><option value="">全部月份</option>${[...months].filter(Boolean).sort().reverse().map(m=>`<option value="${esc(m)}" ${m===filterMonth?'selected':''}>${esc(m)}</option>`).join('')}</select></label><div class="sales-view-toggle"><button class="btn btn-outline-secondary sales-layout-toggle" type="button" data-view="${view==='table'?'cards':'table'}" title="切换为${view==='table'?'卡片':'表格'}显示" aria-label="切换为${view==='table'?'卡片':'表格'}显示"><i class="ti ti-${view==='table'?'layout-cards':'table'} me-1" aria-hidden="true"></i><span>${view==='table'?'卡片':'表格'}</span></button></div>${data.can_submit?'<button class="btn btn-primary" data-new>＋ 登记销售</button>':''}<button class="btn btn-outline-secondary" data-refresh>刷新</button></div>`;
 $('#module-content').innerHTML=`<div class="sales-summary"><span>${esc(filterMonth||'全部月份')} · <strong>${totals.count}</strong> 笔</span><span>销售额 <strong>¥${money(totals.amount)}</strong></span><span>提成金额 <strong>¥${money(totals.commission)}</strong></span><span>已提交未审核 <strong>${totals.pending}</strong> 笔</span><span>已审核销售额 <strong>¥${money(totals.approvedAmount)}</strong></span><span>已审核提成（工资口径） <strong>¥${money(totals.approvedCommission)}</strong></span></div><p class="sales-hint">当前筛选 ${filtered.length} 笔。汇总按统计月份计算，不随结算状态筛选变化；绿色“已提交”表示结算已审核通过。工资表的订单提成对应已审核提成，待审核不计入工资；原表已计提订单保留原金额，不重复发放。${filterMonth?'未选择结算月的订单仍显示，但不计入本月汇总。':''}</p><div class="sales-records" data-view="${view}"><div class="sales-record-cards">${rows.map(claimCard).join('')}</div>${salesTable(rows)}</div>${!filtered.length?'<div class="sales-empty">暂无订单。</div>':''}${filtered.length>visibleCount?`<div class="sales-more"><button class="btn btn-outline-primary" data-more>继续显示（已显示 ${rows.length} / ${filtered.length} 笔）</button></div>`:''}`;
 loadPhotos(rows);
}
function settlementDialog(c){
 if(c.kind==='linked'&&(!linkedOrdersSucceeded(c.orders)||!c.eligible)){modal('系统订单尚不能结算','<p>所有关联订单都必须为“交易成功”才能提交结算，无需填写收货日期。请刷新核对订单状态。</p>');return;}
 const needsReceipt=c.kind==='manual'&&(!c.received_date||c.progress!=='已收货');
 const d=modal('选择结算月',`<form class="sales-settlement-form"><p>${esc(buyerText(c.buyer)||c.title)} · 提成 ¥${money(c.commission)}</p>${needsReceipt?`<label>确认收货日期<input class="form-control" type="date" name="received_date" max="${today()}" required><small class="sales-hint">仅手动订单可补填，填写后标为已收货。</small></label>`:`<p class="sales-hint">${c.kind==='linked'?'所有关联订单均为交易成功，无需填写收货日期。':'确认收货：'+esc(c.received_date)}</p>`}<label>结算月<select class="form-select" name="month" required>${settlementOptions(c.settlement_month||previousMonth(today()))}</select></label><p class="sales-hint">确认选择后即进入待审核，审核通过后计入所选月份工资。</p><div class="sales-error" role="alert"></div><footer><button class="btn btn-primary" type="submit">确认结算月</button></footer></form>`);
 d.querySelector('form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('[type=submit]');btn.disabled=true;try{await api('',{action:'settle',values:{...Object.fromEntries(new FormData(e.target)),id:c.id,version:c.version}});d.close();await load();}catch(e){d.querySelector('.sales-error').textContent=e.message;}finally{btn.disabled=false;}};
}
async function load(){const seq=++sequence,result=await api('?month='+encodeURIComponent(filterMonth));if(seq!==sequence)return;data=result;render();}
async function mutate(action,values){if(busy)return;busy=true;try{await api('',{action,values});await load();return true;}catch(e){message(e.message);return false;}finally{busy=false;}}
async function compress(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('请选择 JPG、PNG 或 WebP 图片');const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>40000000)throw new Error('图片像素过大，请拆成多张截图以保持文字清晰');const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0);let blob=await new Promise(r=>canvas.toBlob(r,'image/webp',.85));if(!blob||blob.type!=='image/webp')blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',.9));const best=blob&&blob.size<file.size?blob:file;if(best.size>12582912)throw new Error('压缩后仍超过 12 MB，请拆分截图');return best;}finally{bitmap.close();}}
function editor(c){
 const adminEdit=Boolean(c&&data.can_approve),saveLabel=adminEdit?'提交修改审核':'保存登记';
 let orders=[...(c?.orders||[])],attachments=[...(c?.attachments||[])];
 const d=modal(c?'编辑销售':'登记企业微信销售',`<form id="sales-edit">${adminEdit?'<p class="sales-hint">管理员修改后进入待审核；选好结算月并审核通过，才计入工资。</p>':''}<div class="sales-fields"><label class="wide">订单类型<select class="form-select" name="kind"><option value="linked">关联系统订单</option><option value="manual">手动输入订单</option></select></label><div class="wide" id="linked-area"><div class="sales-search"><input class="form-control" id="order-query" placeholder="输入订单号，点击搜索才会查询" minlength="4" maxlength="100"><button type="button" class="btn btn-outline-primary" id="order-search">搜索</button></div><div id="order-results"></div><div id="order-selected"></div></div><label class="wide"><span id="buyer-label">旺旺号（可补全）</span><input class="form-control" name="buyer" required maxlength="100" value="${esc(buyerText(c?.buyer))}"></label><div id="manual-number" class="wide"><span>手动订单号</span><p class="sales-hint">${esc(c?.manual_order_no||'保存后自动生成，无需填写')}</p></div><label class="wide" id="manual-title">款式／款号／销售内容<input class="form-control" name="title" maxlength="300" value="${esc(c?.title)}"></label><label id="manual-amount">订单金额<input class="form-control" name="amount" type="number" min="0" step=".01" value="${esc(c?.amount??0)}"></label><label id="manual-progress">订单进度<select class="form-select" name="progress"><option>未发货</option><option>已发货</option><option>已收货</option></select></label><label id="manual-received">确认收货日期（提交审核必填）<input class="form-control" name="received_date" type="date" max="${today()}" value="${esc(c?.received_date||'')}"></label><label id="manual-adjustment">退款／补款调整（选填，减少填负数）<input class="form-control" name="adjustment" type="number" step=".01" value="${esc(c?.adjustment??0)}"></label><label id="manual-adjustment-reason">调整原因<input class="form-control" name="adjustment_reason" maxlength="1000" value="${esc(c?.adjustment_reason)}"></label><div class="wide"><label>聊天截图 <span class="sales-hint">必填 · 最多 12 张</span><span class="sales-upload"><span>＋ 选择聊天截图</span><input name="images" type="file" aria-label="选择聊天截图" accept="image/png,image/jpeg,image/webp" multiple></span></label><p class="sales-hint">自动压缩，保留文字清晰度。原有 ${attachments.length} 张；新增图片保存时上传。</p><div id="local-previews" class="sales-images"></div><div id="saved-images"></div></div><label class="wide">备注（选填）<textarea class="form-control" name="note" maxlength="2000">${esc(c?.note)}</textarea></label></div><div class="sales-error" id="edit-error" role="alert"></div><footer><button class="btn btn-primary" type="submit">${saveLabel}</button></footer></form>`);
 d.classList.add('sales-editor');const form=d.querySelector('form'),el=form.elements;el.kind.value=c?.kind||'linked';el.progress.value=c?.progress||'未发货';let uploads=[],localUrls=[];let buyerEdited=Boolean(c?.buyer&&c.buyer!==[...new Set(orders.map(o=>buyerText(o.buyer)).filter(Boolean))].join(' / '));el.buyer.oninput=()=>{buyerEdited=true;};
 const showOrders=()=>{d.querySelector('#order-selected').innerHTML=orders.map(o=>`<div class="sales-order">${orderPreview(o)}<div class="sales-order-action"><span class="sales-linked">✓ 已关联</span><button type="button" class="btn btn-outline-secondary" data-remove-order="${esc(o.id)}">移除关联</button></div></div>`).join('');if(el.kind.value==='linked'){if(!buyerEdited)el.buyer.value=[...new Set(orders.map(o=>buyerText(o.buyer)).filter(Boolean))].join(' / ');const dates=orders.map(o=>o.received_date);el.received_date.value=dates.length&&dates.every(Boolean)?dates.map(x=>String(x).slice(0,10)).sort().at(-1):'';el.amount.value=orders.reduce((sum,o)=>sum+Number(o.amount||0),0).toFixed(2);el.title.value=orders.map(o=>o.title||(o.items||[]).map(i=>[i.sku,i.name].filter(Boolean).join(' ')).join('、')||o.id).join('；').slice(0,300);}if(!pendingLinkedNotSuccessful(c,el.kind.value,orders))form.querySelector('.sales-withdraw-choice')?.remove();};
 function sync(){const linked=el.kind.value==='linked';d.querySelector('#linked-area').hidden=!linked;for(const id of ['manual-number','manual-title','manual-amount','manual-progress','manual-received','manual-adjustment','manual-adjustment-reason'])d.querySelector('#'+id).hidden=linked;d.querySelector('#buyer-label').textContent=linked?'旺旺号（自动带入，可补全）':'微信号／旺旺号／微信昵称';for(const k of ['title','amount','progress','received_date','adjustment','adjustment_reason'])el[k].disabled=linked;el.amount.readOnly=linked;el.title.readOnly=linked;el.title.required=!linked;el.amount.required=!linked;el.received_date.required=!linked&&el.progress.value==='已收货';el.adjustment_reason.required=!linked&&Number(el.adjustment.value)!==0;showOrders();}
 el.kind.onchange=sync;el.progress.onchange=sync;el.received_date.onchange=()=>{if(el.kind.value==='manual'&&el.received_date.value)el.progress.value='已收货';sync();};el.adjustment.oninput=sync;sync();
 function savedImages(){if(!c)return;d.querySelector('#saved-images').innerHTML=attachments.map(p=>`<div class="sales-saved-image">${thumbnails({attachments:[p]})}<button class="btn btn-sm" type="button" data-remove-image="${esc(p)}">移除</button></div>`).join('');loadPhotos([{...c,attachments}]);}
 savedImages();
 el.images.onchange=()=>{uploads=[];localUrls.forEach(URL.revokeObjectURL);localUrls=[...el.images.files].map(f=>URL.createObjectURL(f));d.querySelector('#local-previews').innerHTML=localUrls.map(u=>`<img src="${u}" alt="待上传聊天截图">`).join('');};d.addEventListener('close',()=>localUrls.forEach(URL.revokeObjectURL));
 let searchController,searchSeq=0;async function search(){const q=d.querySelector('#order-query').value.trim();if(q.length<4){d.querySelector('#edit-error').textContent=errors.sales_search_minimum;return;}
 searchController?.abort();searchController=new AbortController();const seq=++searchSeq;const button=d.querySelector('#order-search');button.textContent='搜索中…';d.querySelector('#edit-error').textContent='';d.querySelector('#order-results').innerHTML='<p class="sales-hint">正在查询订单…</p>';
 try{const result=await api('?q='+encodeURIComponent(q),undefined,{signal:searchController.signal,timeout:12000});if(seq!==searchSeq)return;
 d.querySelector('#order-results').innerHTML=result.orders.map((o,i)=>`<div class="sales-order">${orderPreview(o)}<button type="button" class="btn btn-outline-primary sales-link-button" data-pick="${i}" ${o.claimed&&!orders.some(x=>x.id===o.id)&&!(o.claim_ids||[]).includes(c?.id)?'disabled':''}>${o.claimed&&!orders.some(x=>x.id===o.id)&&!(o.claim_ids||[]).includes(c?.id)?'已被认领':'关联此订单'}</button></div>`).join('')||'<p>当前采集未找到此订单。可核对单号，微信直接付款请选手动订单。</p>';
 d.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{const o=result.orders[Number(b.dataset.pick)];if(!orders.some(x=>x.id===o.id))orders.push(o);showOrders();d.querySelector('#order-results').innerHTML='';});
 }catch(e){if(seq===searchSeq&&e.name!=='AbortError'){d.querySelector('#edit-error').textContent=e.message;d.querySelector('#order-results').innerHTML='';}}finally{if(seq===searchSeq)button.textContent='搜索';}}
 d.addEventListener('close',()=>{searchSeq++;searchController?.abort();});
 d.querySelector('#order-search').onclick=search;d.querySelector('#order-query').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();search();}};
 d.addEventListener('click',e=>{const r=e.target.closest('[data-remove-order]');if(r){orders=orders.filter(o=>o.id!==r.dataset.removeOrder);showOrders();}const a=e.target.closest('[data-remove-image]');if(a){attachments=attachments.filter(p=>p!==a.dataset.removeImage);a.parentElement.remove();}});
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]'),withdraw=Boolean(form.querySelector('[name=withdraw_settlement]:checked'));button.disabled=true;try{const files=[...el.images.files];if(attachments.length+files.length<1||attachments.length+files.length>12)throw new Error(errors.sales_images_required);if(el.kind.value==='linked'&&!orders.length)throw new Error(errors.sales_order_required);if(pendingLinkedNotSuccessful(c,el.kind.value,orders)&&!withdraw){if(c.owner_id===data.user_id&&!form.querySelector('[name=withdraw_settlement]')){const choice=document.createElement('label');choice.className='sales-withdraw-choice';choice.innerHTML='<input type=checkbox name=withdraw_settlement> 撤回本次结算并保存关联，保存后回到“未提交”';d.querySelector('#edit-error').before(choice);}throw new Error(errors.sales_order_not_successful);}
 for(let i=uploads.length;i<files.length;i++){button.textContent=`正在压缩上传 ${i+1}/${files.length}`;const blob=await compress(files[i]);const ticket=await api('/upload',{type:blob.type,size:blob.size});const {error}=await window.JUN_SUPABASE.storage.from(ticket.bucket).uploadToSignedUrl(ticket.path,ticket.token,blob,{contentType:blob.type});if(error)throw error;uploads.push(ticket.path);}
 const fields=Object.fromEntries(new FormData(form));delete fields.withdraw_settlement;const v=saleValues(fields,c,orders,[...attachments,...uploads],withdraw);await api('',{action:'save',values:v});d.close();await load();}catch(e){d.querySelector('#edit-error').textContent=e.message;}finally{button.disabled=false;button.textContent=saveLabel;}};
}
function imageUrl(url){if(!url)return '';const at=url.indexOf('/storage/v1/');if(at<0)return '';return window.JUN_CONFIG.supabaseUrl.replace(/\/$/,'')+url.slice(at);}
function evidence(c,urls){c={...c,claim_amount:c.claim_amount??(Number(c.amount||0)+Number(c.adjustment||0)),commission:c.commission??Math.round((Number(c.amount||0)+Number(c.adjustment||0))*5)/100};return `<h4>${esc(c.title)}</h4><p>${c.kind==='linked'?'关联订单':'手动输入订单'} · 计提金额 ¥${money(c.claim_amount)} · 提成 ¥${money(c.commission)}</p><p>${esc(buyerText(c.buyer))}${c.kind==='manual'?' · 单号 '+esc(c.manual_order_no||c.reference||'—'):''}</p>${c.import_meta?.order_refs?.length?`<div class="sales-record-refs">${c.import_meta.order_refs.map(x=>`<div>${esc(x)}</div>`).join('')}</div>`:''}${c.settlement_month?`<p>结算月份 ${esc(c.settlement_month)} · ${statusText(c)}</p>`:''}${c.import_meta?.receipt_text?.length?`<p class="sales-hint">原表收货状态：${esc(c.import_meta.receipt_text.join(' / '))}${!c.received_date?'；未提供具体收货日期':''}</p>`:''}${(c.orders||[]).map(orderPreview).join('')}<p class="sales-note">${esc(c.note)}${c.adjustment_reason?'\n调整 '+money(c.adjustment)+'：'+esc(c.adjustment_reason):''}</p><div class="sales-images">${(c.attachments||[]).map(p=>`<a href="${esc(imageUrl(urls[p]))}" target="_blank" rel="noopener"><img loading="lazy" src="${esc(imageUrl(urls[p]))}" alt="聊天截图，点击查看清晰图"></a>`).join('')}</div>`;}
function archiveEvidence(r,urls){const names={B:'旺旺号',C:'订单号',E:'金额',F:'确认收货',H:'付款方式／补充说明',I:'备注1',J:'备注2',K:'提成金额',L:'提成结算月'};return `<h3>原表第 ${r.source_row} 行 · ${esc(r.month||'结算月未填写')}</h3>${Object.entries(r.cells).filter(([a,c])=>c.v||c.f).map(([a,c])=>`<p class="sales-note"><strong>${esc(names[a.replace(/\d/g,'')]||a)}（${a}）</strong>：${esc(a.startsWith('L')&&r.month?r.month:c.v)}${c.f?`<small>　公式 ${esc(c.f)}</small>`:''}</p>`).join('')}<p class="sales-hint">相关合并单元格：${esc((r.merges||[]).join('、')||'无')}</p><div class="sales-images">${(r.attachments||[]).map(p=>`<a href="${esc(imageUrl(urls[p]))}" target="_blank" rel="noopener"><img loading="lazy" src="${esc(imageUrl(urls[p]))}" alt="原表截图"></a>`).join('')}</div>`;}
async function detail(id,kind){const d=modal('销售明细','正在读取…');try{const r=await api('/detail?id='+id+'&kind='+kind);const editable=kind==='batch'&&r.record.status==='pending'&&(data.can_approve||r.record.owner_id===data.user_id&&data.can_submit);d.querySelector('.sales-body').innerHTML=(kind==='archive'?archiveEvidence(r.record,r.urls):kind==='batch'?`<h3>${esc(r.record.month)} · ${labels[r.record.status]}</h3>${r.record.items.map(c=>evidence(c,r.urls)+(editable?`<button class="btn btn-sm" data-edit-pending="${c.id}">编辑订单</button>`:'')).join('<hr>')}`:evidence(r.record,r.urls)+(r.can_edit?`<button class="btn" data-edit-pending="${r.record.id}">编辑订单</button>`:''))+(data.can_approve?`<h3>修改与审批记录</h3>${r.history.map(h=>`<details class="sales-history"><summary>${esc(h.created_at)} · ${esc(h.actor_name)} · ${esc(({settle:'选择结算月提交',import:'批量导入',save:'保存登记',edit:'修改订单并更新月单',submit:'选择结算月提交',approve:'审核通过',reject:'退回修改',withdraw:'撤回'})[h.action]||h.action)}</summary>${h.payload.reason?`<p>${esc(h.payload.reason)}</p>`:''}${h.payload.before?'<h4>修改前</h4>'+evidence(h.payload.before,r.urls):''}${h.payload.after?'<h4>修改后</h4>'+evidence(h.payload.after,r.urls):''}${(h.payload.items||[]).map(c=>evidence(c,r.urls)).join('<hr>')}</details>`).join('')}`:'');}catch(e){d.querySelector('.sales-body').textContent=e.message;}}
async function editPending(id,dialog){try{const r=await api('/detail?id='+id+'&kind=claim');if(!r.can_edit)throw new Error('该订单已经定稿，不能修改');dialog?.close();editor(r.record);}catch(e){message(e.message);}}
function confirmAction(action,b){const d=modal(action==='submit'?'确认月度提成单':({approve:'审核通过',reject:'退回修改',withdraw:'撤回提成单'})[action],`<form><p>${action==='submit'?`${esc(month)}：关联订单须全部交易成功；手动订单须填写收货日期。在订单上选择结算月提交审核。`:action==='approve'?'通过后，这笔订单的提成计入所选结算月工资；该订单不能再修改。':action==='withdraw'?'撤回后订单恢复未提交状态，可重新选择结算月，原记录保留。':'填写需要修改的内容，申请人修改后重新提交。'}</p>${action==='reject'?'<textarea class="form-control" name="reason" required maxlength="1000" placeholder="退回原因"></textarea>':''}<footer><button class="btn btn-primary" type="submit">确认${action==='submit'?'提交':''}</button></footer></form>`);d.querySelector('form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('button');btn.disabled=true;const claims=[];const values=action==='submit'?{month,ids:claims.map(c=>c.id),expected:claims.map(c=>({id:c.id,version:c.version,amount:c.claim_amount,orders:c.orders}))}:{id:b.id,version:b.version,reason:new FormData(e.target).get('reason')||''};if(await mutate(action,values)){d.close();if(action==='submit'){selected.clear();filterStatus='pending';render();}}else {btn.disabled=false;let err=d.querySelector('.sales-error');if(!err){err=document.createElement('p');err.className='sales-error';d.querySelector('form').prepend(err);}err.textContent=$('#sales-message')?.textContent||'提交失败，请重试';}};}
document.addEventListener('change',e=>{if(e.target.id==='sales-filter-status'){filterStatus=normalizeSettlementFilter(e.target.value);visibleCount=30;const u=new URL(location);filterStatus?u.searchParams.set('settlement',filterStatus):u.searchParams.delete('settlement');history.replaceState(null,'',u);render();}if(e.target.id==='sales-filter-month'){filterMonth=e.target.value;visibleCount=30;const u=new URL(location);filterMonth?u.searchParams.set('month',filterMonth):u.searchParams.delete('month');history.replaceState(null,'',u);load().catch(e=>message(e.message));}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.photo){viewPhoto(b.dataset.photo);return;}if(b.dataset.settlement){settlementDialog(data.claims.find(c=>c.id===b.dataset.settlement));return;}if(b.dataset.view){view=b.dataset.view;try{localStorage.setItem('jun-sales-view',view);}catch{}render();}if(b.hasAttribute('data-more')){visibleCount+=30;render();}if(b.hasAttribute('data-new'))editor();if(b.dataset.editPending)editPending(b.dataset.editPending,b.closest('dialog'));if(b.dataset.edit)editor(data.claims.find(c=>c.id===b.dataset.edit));if(b.dataset.detail)detail(b.dataset.detail,b.dataset.kind);if(b.hasAttribute('data-refresh'))load().catch(e=>message(e.message));if(b.hasAttribute('data-submit'))confirmAction('submit');if(b.dataset.action)confirmAction(b.dataset.action,data.batches.find(x=>x.id===b.dataset.id));});
Promise.resolve(window.JUN_AUTH_READY).then(load).catch(e=>message(e.message));
})(typeof window!=='undefined'?window:globalThis);
