(function () {
  'use strict';
  if(new URLSearchParams(location.search).get('view')==='workflow')return;
  const app=document.getElementById('erp-app');
  const state={page:0,limit:50,total:0,finance:false,rows:[],q:'',month:'',basis:'created',status:'',source:'',seq:0};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const amount=v=>v===null||v===undefined||v===''?'—':new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY'}).format(Number(v));
  const stamp=v=>v?esc(String(v).replace('T',' ').slice(0,19)):'—';
  const names={erp:'管家婆','erp.raw':'管家婆完整采集','qianniu.export':'千牛历史','qianniu.incremental':'千牛增量','qianniu.refund':'退款管理','finance.taobao_income_order':'账房货款','finance.taobao_platform_charge':'账房费用',manual:'手动订单'};
  const labels={raw_json:'原始采集字段',source:'来源',month:'账期',groups:'待办分类',coverage:'覆盖说明',fetched_at:'采集时间',trade_created_at:'平台下单时间',service_fee:'服务费',has_merge:'合单标记',has_split:'拆单标记',order_total:'订单总额',trade_total:'交易总额',settle_total:'结算额',report_total:'报表金额',pay_no:'支付单号',order_id:'订单号',status:'状态',paid_at:'付款时间',created_at:'下单时间',completed_at:'确认收货时间',shipped_at:'发货时间',source_observed_at:'采集时间',observed_at:'采集时间',detail_observed_at:'详情采集时间',refund_amount:'导出退款金额',buyer_paid_amount:'导出实付金额',merchant_received_amount:'确认收货打款金额',buyer_due_goods:'应付货款',buyer_due_shipping:'应付邮费',gross_amount:'报表总金额',listed_amount:'列表金额',refund_id:'退款单号',success_at:'退款成功时间',amount:'金额',refunds:'退款记录',after_sales:'售后记录',detail:'详情',status_raw:'平台原始状态',money_quality:'金额核对情况',net_amount:'净额',successful_refund_amount:'详情成功退款合计',kind:'类型',dispute_id:'售后单号',items:'商品明细',id:'来源订单号',vchcode:'管家婆单据号',sku:'SKU',sku_full:'完整SKU',name:'名称',qty:'数量',price:'单价',trade_status:'交易状态',process_status:'处理状态',seller_memo:'卖家备注',buyer_message:'买家留言',buyer:'买家',shop:'店铺',tracking_no:'物流单号',logistics_company:'物流公司',warehouse:'仓库',operator:'经办人',freight:'运费',discount:'优惠',refund_status:'售后状态',audit_fail_reason:'审核异常',tag:'标签',alert:'提示',refundFee:'申请退款金额',transactionAmount:'交易金额',refundStatus:'退款状态',refundReason:'退款原因',applyDateTime:'申请时间',tradeId:'淘宝订单号',itemTitle:'商品',returnLogisticsDetail:'退货物流详情',deliveryStatus:'物流状态',remaining:'处理期限',operations:'可用操作',candidateIds:'关联标识',logistics:'退货物流',manual_order_no:'手动订单号',received_date:'收货日期',progress:'订单进度',title:'标题',note:'备注',attachments:'附件'};
  async function api(path){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(path,{signal:controller.signal});const p=await r.json();if(!r.ok)throw new Error(p.detail||p.error||`HTTP ${r.status}`);return p;}catch(e){throw new Error(e.name==='AbortError'?'请求超时，请重试':e.message);}finally{clearTimeout(timer);}}
  function fields(obj,depth=0){if(obj===null||obj===undefined||obj==='')return '<span class="text-secondary">未采集</span>';if(typeof obj!=='object')return esc(obj);if(depth>7)return esc(JSON.stringify(obj));if(Array.isArray(obj))return obj.length?obj.map((v,i)=>`<div class="oc-array-item"><small>${i+1}</small>${fields(v,depth+1)}</div>`).join(''):'<span class="text-secondary">暂无记录</span>';return `<dl class="oc-fields">${Object.entries(obj).filter(([k])=>!k.startsWith('_')).map(([k,v])=>`<dt>${esc(labels[k]||k)}</dt><dd>${fields(v,depth+1)}</dd>`).join('')}</dl>`;}
  function shell(){app.innerHTML=`<div class="oc-toolbar"><a class="btn btn-outline-secondary" href="?view=workflow">管家婆处理进度</a><button class="btn btn-primary" id="oc-refresh">刷新</button><span id="oc-status" role="status">正在加载订单…</span></div><form id="oc-filters" class="oc-filters"><label>搜索<input name="q" class="form-control" placeholder="订单号、备注或物流单号"></label><label>月份<input name="month" type="month" class="form-control"></label><label>日期口径<select name="basis" class="form-select"><option value="created">下单月份</option><option value="paid">付款月份</option><option value="completed">确认收货月份</option><option value="billing" id="oc-billing-option" hidden>账房流水月份</option></select></label><label>交易状态<select name="status" class="form-select"><option value="">全部</option><option>交易成功</option><option>交易关闭</option><option>未付款关闭</option><option>买家已付款</option><option>卖家已发货</option></select></label><label>数据来源<select name="source" class="form-select"><option value="">全部</option>${Object.entries(names).map(([k,v])=>`<option value="${esc(k)}">${esc(v)}</option>`).join('')}</select></label><button class="btn btn-primary" type="submit">查询</button><button class="btn btn-outline-secondary" id="oc-clear" type="button">清空</button></form><div id="oc-coverage" class="text-secondary mb-3"></div><div id="oc-results"></div><dialog id="oc-detail" class="oc-dialog"><header><h3 id="oc-detail-title">订单详情</h3><button class="btn btn-outline-secondary" data-close>关闭</button></header><div id="oc-detail-body"></div></dialog><dialog id="oc-refund" class="oc-dialog"><header><h3>退款 / 售后详情</h3><button class="btn btn-outline-secondary" data-close>关闭</button></header><div id="oc-refund-body"></div></dialog>`;
  document.getElementById('oc-filters').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);for(const k of ['q','month','basis','status','source'])state[k]=String(f.get(k)||'');state.page=0;load();});document.getElementById('oc-refresh').onclick=()=>load();document.getElementById('oc-clear').onclick=()=>{document.getElementById('oc-filters').reset();Object.assign(state,{q:'',month:'',basis:'created',status:'',source:'',page:0});load();};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());}
  function render(){document.getElementById('oc-results').innerHTML=`<div class="oc-toolbar">${Object.entries(state.states||{}).map(([k,v])=>`<span class="badge bg-secondary-lt">${esc(k)} ${esc(v)}</span>`).join('')}</div><div class="oc-table-wrap"><table class="table table-vcenter oc-table"><thead><tr><th>订单号 / 来源</th><th>状态 / 售后</th><th>下单 / 付款</th><th>确认收货</th><th>订单导出金额</th>${state.finance?'<th>账房累计已入账</th>':''}<th>处理 / 物流</th></tr></thead><tbody>${state.rows.map(o=>`<tr><td><button type="button" class="oc-link" data-order="${esc(o.order_id)}">${esc(o.order_id)}</button><small>${(o.sources||[]).map(s=>esc(names[s]||s)).join(' · ')}</small>${o.erp_records>1?`<small>管家婆 ${o.erp_records} 条拆分记录</small>`:''}</td><td>${esc(o.unpaid_closed?'未付款关闭':o.status)}${o.refund_marked?'<small class="text-orange">有退款 / 售后记录</small>':''}</td><td>${stamp(o.created_at)}<small>付款 ${stamp(o.paid_at)}</small></td><td>${stamp(o.completed_at)}</td><td>${amount(o.export_paid??o.manual_amount)}<small>导出退款 ${amount(o.export_refund)}</small>${o.export_paid==null&&o.erp_amount!=null?`<small>ERP ${amount(o.erp_amount)}</small>`:''}</td>${state.finance?`<td>${Number(o.billing?.rows)>0?amount(o.billing.net):'未匹配流水'}<small>${(o.billing?.months||[]).filter(Boolean).map(esc).join('、')}</small></td>`:''}<td>${esc(o.process_status||o.tag||'—')}<small>${esc(o.tracking_no||'')}</small></td></tr>`).join('')||'<tr><td colspan="7">没有符合条件的订单</td></tr>'}</tbody></table></div><div class="oc-pager"><span>共 ${state.total} 单 · 第 ${state.page+1} / ${Math.max(1,Math.ceil(state.total/state.limit))} 页</span><button class="btn btn-outline-secondary" id="oc-prev" ${state.page===0?'disabled':''}>上一页</button><button class="btn btn-outline-secondary" id="oc-next" ${(state.page+1)*state.limit>=state.total?'disabled':''}>下一页</button></div>`;
  document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>detail(b.dataset.order));document.getElementById('oc-prev').onclick=()=>{state.page--;load();};document.getElementById('oc-next').onclick=()=>{state.page++;load();};}
  async function load(){const seq=++state.seq;const status=document.getElementById('oc-status');status.textContent='正在加载订单…';try{const q=new URLSearchParams({q:state.q,month:state.month,date_basis:state.basis,status:state.status,source:state.source,limit:String(state.limit),offset:String(state.page*state.limit)});const p=await api('/api/orders?'+q);if(seq!==state.seq)return;state.rows=p.orders||[];state.total=p.total||0;state.finance=p.finance_visible===true;state.states=p.states||{};document.getElementById('oc-billing-option').hidden=!state.finance;document.getElementById('oc-coverage').textContent=state.finance?`账房已采集账期：${(p.billing_months||[]).join('、')||'暂无'}。金额按订单关联各月流水；列表净额为已采集账期累计，缺失月份不按零处理。`:'点击订单查看各来源明细、商品、时间和售后信息。';status.textContent=`已加载 ${state.rows.length} 单${p.unlinked_count?' · '+p.unlinked_count+' 条来源待关联':''}`;render();}catch(e){if(seq===state.seq){status.textContent=e.message;document.getElementById('oc-results').innerHTML='<div class="alert alert-warning">订单暂时未能加载，请点击刷新重试。</div>';}}}
  let detailSeq=0;
  async function detail(id){const seq=++detailSeq;const d=document.getElementById('oc-detail'),body=document.getElementById('oc-detail-body');document.getElementById('oc-detail-title').textContent='订单 '+id;body.textContent='正在加载…';if(!d.open)d.showModal();try{const p=await api('/api/orders/'+encodeURIComponent(id));if(seq!==detailSeq)return;const o=p.order;const sources=p.sources||[];const refunds=[];for(const s of sources){if(s.source==='qianniu.refund')refunds.push({source:'退款管理',observed_at:s.observed_at,...s.payload});if(s.source==='qianniu.incremental')for(const r of [...(s.payload.detail?.refunds||[]),...(s.payload.detail?.after_sales||[])])refunds.push({source:'千牛详情',...r});if(s.source==='finance.taobao_income_order'&&Number(s.payload['退款金额（元）'])>0)refunds.push({source:'账房退款流水',month:s.month,...s.payload});}
  body.innerHTML=`<div class="oc-summary"><div><small>交易状态</small><strong>${esc(o.status)}</strong></div><div><small>导出实付</small><strong>${amount(o.export_paid)}</strong></div><div><small>导出退款</small><strong>${amount(o.export_refund)}</strong></div>${p.finance_visible?`<div><small>账房累计净收</small><strong>${Number(o.billing?.rows)>0?amount(o.billing.net):'未匹配流水'}</strong></div>`:''}</div><p class="text-secondary">订单金额保留原字段；导出实付不再重复扣导出退款。账房净收仅覆盖已列账期，平台费用另列。</p><button class="btn btn-outline-primary mb-3" id="oc-open-refunds">退款 / 售后详情（${refunds.length} 条来源记录）</button>${sources.map(s=>`<details class="oc-source" ${['qianniu.export','qianniu.incremental'].includes(s.source)?'open':''}><summary>${esc(names[s.source]||s.source)}${s.month?' · '+esc(s.month):''}${s.active?'':' · 历史批次'} <small>采集 ${stamp(s.observed_at)}</small></summary>${fields(s.payload)}</details>`).join('')}<details class="oc-source"><summary>已记录的变化（最近 ${(p.history||[]).length} 条）</summary>${(p.history||[]).map(h=>`<details><summary>${esc(names[h.source]||h.source)} · ${stamp(h.observed_at)}</summary>${fields(h.payload)}</details>`).join('')||'<p>本次接入后的变化会继续保留；此前未记录的历史不作推断。</p>'}</details>`;
  document.getElementById('oc-open-refunds').onclick=()=>{const r=document.getElementById('oc-refund');document.getElementById('oc-refund-body').innerHTML='<p class="text-secondary">各来源可能描述同一退款，请按退款单号及流水号核对；不把不同来源金额重复相加。</p>'+ (refunds.length?refunds.map(x=>`<section class="oc-source">${fields(x)}</section>`).join(''):'<p>当前已采集来源没有可展开的退款明细，不代表没有发生退款。</p>');r.showModal();};}catch(e){if(seq===detailSeq)body.textContent=e.message;}}
  (async()=>{try{await window.JUN_AUTH_READY;shell();await load();}catch(e){app.textContent='订单情况加载失败：'+e.message;}})();
})();
